FEPiCpp: iMarkedEntity Class Reference
iMarkedEntity Class Reference
#include <entities.hpp>
Inherited by iEdge< Traits >, iMarkedHalfEdge< Traits >, iMarkedHalfFace< Traits >, iPoint< Traits >, iPolygon< Traits >, and iPolyhedron< Traits >.
Public Member Functions
iMarkedEntity (int Label, bool Isdead=false, bool MustBK=false, bool otherf=false)
iMarkedEntity ()
int getLabel () const
void setLabel (unsigned char const &c)
void resetFlags ()
bool isDead () const
bool mustBeKilled () const
void killMe ()
void reviveMe ()
void killMeLater ()
void dontKillMe ()
~iMarkedEntity ()
Protected Attributes
unsigned char _label
Static Protected Attributes
static const unsigned char FlagsMask = 7
static const int OffSet = 3
Detailed Description
Interface para armazenar um rótulo e 3 flags. Esses atributos são compactados em um único char. Os 3 primeiros bits do char são para armazenar os flags:
char[0] := "isdead" ?;
char[1] := "must be killed" ?;
char[2] := "other flags"
O restante é para armazenar o rótulo (inteiro de 0 a 31 se o char for de 8 bits).
Definition at line 279 of file entities.hpp.
Constructor & Destructor Documentation
iMarkedEntity::iMarkedEntity (int Label, bool Isdead = false, bool MustBK = false, bool otherf = false) [inline]
Parameters:
Label O rótulo (inteiro de 0 a 31).
Isdead true se está morto ou false caso contrário.
MustBK true se deve ser morto ou false caso contrário.
otherf Um flag qualquer. Ainda não lhe foi atribuído nenhuma função.
Definition at line 287 of file entities.hpp.
References _label, OffSet, set_bit(), and unset_bit().
        {
                _label = (unsigned char)(Label << OffSet);
                Isdead ? set_bit(_label,0) : unset_bit(_label,0);
                MustBK ? set_bit(_label,1) : unset_bit(_label,1);
                otherf ? set_bit(_label,2) : unset_bit(_label,2);
        }
iMarkedEntity::iMarkedEntity () [inline]
Definition at line 295 of file entities.hpp.
References _label.
        {
                _label = 0;
        };
iMarkedEntity::~iMarkedEntity () [inline]
Definition at line 364 of file entities.hpp.
{}
Member Function Documentation
void iMarkedEntity::dontKillMe () [inline]
Limpa o flag "must be killed".
Definition at line 360 of file entities.hpp.
References _label, and unset_bit().
{
                unset_bit(_label,1);
        }
int iMarkedEntity::getLabel () const [inline]
Returns:
O rótulo.
Definition at line 302 of file entities.hpp.
References _label, and OffSet.
Referenced by iPolyhedron< Traits >::propagateLabel(), iPolygon< Traits >::propagateLabel(), iMarkedHalfFace< Traits >::propagateLabel(), and iMarkedHalfEdge< Traits >::propagateLabel().
        {
                return int(_label >> OffSet);
        }
bool iMarkedEntity::isDead () const [inline]
Returns:
true se está morto ou false caso contrário.
Definition at line 325 of file entities.hpp.
References _label, and get_bit().
        {
                return get_bit(_label,0);
        }
void iMarkedEntity::killMe () [inline]
Seta o flag "isdead".
Definition at line 339 of file entities.hpp.
References _label, and set_bit().
        {
                set_bit(_label,0);
        }
void iMarkedEntity::killMeLater () [inline]
Seta o flag "must be killed".
Definition at line 353 of file entities.hpp.
References _label, and set_bit().
        {
                set_bit(_label,1);
        }
bool iMarkedEntity::mustBeKilled () const [inline]
Returns:
true se deve ser morto ou false caso contrário.
Definition at line 332 of file entities.hpp.
References _label, and get_bit().
        {
                return get_bit(_label,1);
        }
void iMarkedEntity::resetFlags () [inline]
Limpa os flags.
Definition at line 318 of file entities.hpp.
References _label, and FlagsMask.
        {
                _label &= (~FlagsMask);
        }
void iMarkedEntity::reviveMe () [inline]
Limpa o flag "isdead".
Definition at line 346 of file entities.hpp.
References _label, and unset_bit().
        {
                unset_bit(_label,0);
        }
void iMarkedEntity::setLabel (unsigned char const & c) [inline]
Seta o rótulo.
Parameters:
c O rótulo.
Definition at line 310 of file entities.hpp.
References _label, FlagsMask, and OffSet.
        {
                _label &= FlagsMask;
                _label |= (c << OffSet);
        }
Member Data Documentation
unsigned char iMarkedEntity::_label [protected]
Definition at line 369 of file entities.hpp.
Referenced by dontKillMe(), getLabel(), iMarkedEntity(), isDead(), killMe(), killMeLater(), mustBeKilled(), resetFlags(), reviveMe(), and setLabel().
const unsigned char iMarkedEntity::FlagsMask = 7 [static, protected]
Definition at line 370 of file entities.hpp.
Referenced by resetFlags(), and setLabel().
const int iMarkedEntity::OffSet = 3 [static, protected]
Definition at line 371 of file entities.hpp.
Referenced by getLabel(), iMarkedEntity(), and setLabel().
The documentation for this class was generated from the following file:
entities.hpp