FEPiCpp: Tetrahedron< Traits > Class Template Reference
Tetrahedron< Traits > Class Template Reference
#include <tetrahedron.hpp>
Inherits _Poly3d< Traits >.
Classes
class iCellData
Public Types
typedef Simplex< 3 > ElmClass
typedef Tetrahedron< Traits > VolumeT
typedef Triangle< Traits > FaceT
typedef FaceT BorderT
typedef Edge< Traits > BndBorderT
typedef BndBorderT EdgeT
typedef Traits::PointT PointT
typedef Traits::MeshT MeshT
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
Tetrahedron ()
Tetrahedron (Fepic::vectorui const &nodes, int label=0)
Tetrahedron (Fepic::vectorui &&nodes, int label=0)
void printSelfVtk (std::ostream &o, int order) const
void setOrder (int order)
Static Public Member Functions
static int getNumNodesCell (int order)
static int getCellTypeVtk ()
static int getMshTag (int order)
static Fepic::matrixi getEdgesLocalNodes (int order)
static Fepic::matrixi getFacesLocalNodes (int order)
static Fepic::vectori getOppELN (int n)
static Fepic::matrixi getOppFLN (int n)
static int getNumCellsMM (int n)
static std::string name ()
Static Public Attributes
static const int Dim = 3
Detailed Description
template<class Traits>
class Tetrahedron< Traits >
Definition at line 28 of file tetrahedron.hpp.
Member Typedef Documentation
template<class Traits > typedef Edge<Traits> Tetrahedron< Traits >::BndBorderT
Definition at line 36 of file tetrahedron.hpp.
template<class Traits > typedef FaceT Tetrahedron< Traits >::BorderT
Definition at line 35 of file tetrahedron.hpp.
template<class Traits > typedef BndBorderT Tetrahedron< Traits >::EdgeT
Definition at line 37 of file tetrahedron.hpp.
template<class Traits > typedef Simplex<3> Tetrahedron< Traits >::ElmClass
Definition at line 32 of file tetrahedron.hpp.
template<class Traits > typedef Triangle<Traits> Tetrahedron< Traits >::FaceT
Reimplemented from _Poly3d< Traits >.
Definition at line 34 of file tetrahedron.hpp.
template<class Traits > typedef Traits::MeshT Tetrahedron< Traits >::MeshT
Reimplemented from _Poly3d< Traits >.
Definition at line 39 of file tetrahedron.hpp.
template<class Traits > typedef Traits::PointT Tetrahedron< Traits >::PointT
Definition at line 38 of file tetrahedron.hpp.
template<class Traits > typedef Eigen::Matrix<double, Traits::spacedim, 1> Tetrahedron< Traits >::VecT
Reimplemented from _Poly3d< Traits >.
Definition at line 41 of file tetrahedron.hpp.
template<class Traits > typedef Tetrahedron<Traits> Tetrahedron< Traits >::VolumeT
Definition at line 33 of file tetrahedron.hpp.
Constructor & Destructor Documentation
template<class Traits > Tetrahedron< Traits >::Tetrahedron () [inline]
Definition at line 43 of file tetrahedron.hpp.
template<class Traits > Tetrahedron< Traits >::Tetrahedron (Fepic::vectorui const & nodes, int label = 0) [inline]
Parameters:
nodes vetor com os nós que compõe o polígono.
Definition at line 49 of file tetrahedron.hpp.
template<class Traits > Tetrahedron< Traits >::Tetrahedron (Fepic::vectorui && nodes, int label = 0) [inline]
Parameters:
nodes vetor com os nós que compõe o polígono.
Definition at line 55 of file tetrahedron.hpp.
Member Function Documentation
template<class Traits > static int Tetrahedron< Traits >::getCellTypeVtk () [inline, static]
Definition at line 84 of file tetrahedron.hpp.
template<class Traits > static Fepic::matrixi Tetrahedron< Traits >::getEdgesLocalNodes (int order) [inline, static]
INICIALIZADOR ... NÃO UTILIZAR
Definition at line 117 of file tetrahedron.hpp.
Referenced by Tetrahedron< Traits >::getFacesLocalNodes().
template<class Traits > static Fepic::matrixi Tetrahedron< Traits >::getFacesLocalNodes (int order) [inline, static]
INICIALIZADOR ... NÃO UTILIZAR
Definition at line 139 of file tetrahedron.hpp.
References Tetrahedron< Traits >::getEdgesLocalNodes().
template<class Traits > static int Tetrahedron< Traits >::getMshTag (int order) [inline, static]
Definition at line 89 of file tetrahedron.hpp.
template<class Traits > static int Tetrahedron< Traits >::getNumCellsMM (int n) [inline, static]
Retorna o número de mini-células de uma mini-malha de ordem n.
Definition at line 282 of file tetrahedron.hpp.
template<class Traits > static int Tetrahedron< Traits >::getNumNodesCell (int order) [inline, static]
Retorna o número de nós desse poliedro.
Definition at line 61 of file tetrahedron.hpp.
template<class Traits > static Fepic::vectori Tetrahedron< Traits >::getOppELN (int n) [inline, static]
NOT FOR USERS
Parameters:
n ordem
Definition at line 194 of file tetrahedron.hpp.
template<class Traits > static Fepic::matrixi Tetrahedron< Traits >::getOppFLN (int n) [inline, static]
NOT FOR USERS
getOppFLN(n)[anchor] = vetor com a visão da face oposta de âncora anchor.
Parameters:
n ordem
Definition at line 211 of file tetrahedron.hpp.
References genTriParametricPtsINT().
template<class Traits > static std::string Tetrahedron< Traits >::name () [inline, static]
Definition at line 432 of file tetrahedron.hpp.
template<class Traits > void Tetrahedron< Traits >::printSelfVtk (std::ostream & o, int order) const [inline]
Definition at line 66 of file tetrahedron.hpp.
References Tetrahedron< Traits >::iCellData::getMinimesh(), and _Poly3d< Traits >::getNodeIdx().
template<class Traits > void Tetrahedron< Traits >::setOrder (int order) [inline]
Warning:
Toda vez que a ordem da malha for alterada, essa função DEVE SER CHAMADA.
Definition at line 109 of file tetrahedron.hpp.
References _Poly3d< Traits >::_node.
Member Data Documentation
template<class Traits > const int Tetrahedron< Traits >::Dim = 3 [static]
Reimplemented from _Poly3d< Traits >.
Definition at line 30 of file tetrahedron.hpp.
The documentation for this class was generated from the following file:
tetrahedron.hpp