FEPiCpp: iMarkedHalfFace< Traits > Class Template Reference
iMarkedHalfFace< Traits > Class Template Reference
#include <entities.hpp>
Inherits iHalfFace< Traits >, and iMarkedEntity.
Public Types
typedef Traits::MeshT MeshT
typedef Traits::CellT CellT
Public Member Functions
iMarkedHalfFace (uint cellid, int ith, int anchor, int label=0)
iMarkedHalfFace ()
void propagateHalf (MeshT &mesh) const
void propagateLabel (MeshT &mesh, bool force=false) const
~iMarkedHalfFace ()
Detailed Description
template<class Traits>
class iMarkedHalfFace< Traits >
Trata-se da classe iHalfFace com herança de classe iMarkedEntity.
Definition at line 809 of file entities.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::CellT iMarkedHalfFace< Traits >::CellT
Definition at line 814 of file entities.hpp.
template<class Traits > typedef Traits::MeshT iMarkedHalfFace< Traits >::MeshT
Definition at line 813 of file entities.hpp.
Constructor & Destructor Documentation
template<class Traits > iMarkedHalfFace< Traits >::iMarkedHalfFace (uint cellid, int ith, int anchor, int label = 0) [inline]
Construtor.
Parameters:
cellid o iD da célula incidente.
ith a posição da aresta nesta célula.
anchor o índice âncora.
label o rótulo.
Definition at line 823 of file entities.hpp.
                                                                       : iHalfFace<Traits> (cellid, ith, anchor),
                                                                                                                                         iMarkedEntity(label) {}
template<class Traits > iMarkedHalfFace< Traits >::iMarkedHalfFace () [inline]
Definition at line 826 of file entities.hpp.
: iHalfFace<Traits>(), iMarkedEntity() {}
template<class Traits > iMarkedHalfFace< Traits >::~iMarkedHalfFace () [inline]
Destrutor.
Definition at line 871 of file entities.hpp.
{}
Member Function Documentation
template<class Traits > void iMarkedHalfFace< Traits >::propagateHalf (MeshT & mesh) const [inline]
Faz com que cada nó desta iMarkedHalfFace aponte para ela.
Parameters:
mesh a malha na qual a iMarkedHalfFace está contida.
Definition at line 831 of file entities.hpp.
References iHalfFace< Traits >::getIDCell(), and iHalfFace< Traits >::getIDPosition().
        {
                Fepic::vectorui v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(),mesh );
                for (uint i = 0; i < v.size(); i++)
                {
                        mesh.getNode(v[i])->setHalf(*this);
                }
        }
template<class Traits > void iMarkedHalfFace< Traits >::propagateLabel (MeshT & mesh, bool force = false) const [inline]
Atribui o rótulo desta iMarkedHalfEdge a seus nós.
Parameters:
force quando true indica atribuição incondicional, quando false, a atribuição é feita somente se cada nó tem label=0;
Definition at line 846 of file entities.hpp.
References iHalfFace< Traits >::getIDCell(), iHalfFace< Traits >::getIDPosition(), and iMarkedEntity::getLabel().
        {
                Fepic::vectori v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(),mesh );
                if (force)
                {
                        for (int i = 0; i < v.size(); ++i)
{
                                mesh.getNode(v[i])->setLabel(this->getLabel());
                        }
                }
                else
                {
                        for (int i = 0; i < v.size(); i++)
{
                                if (mesh.getNode(v[i])->getLabel() == 0)
{
                                        mesh.getNode(v[i])->setLabel(this->getLabel());
                                }
                        }
                }
        }
The documentation for this class was generated from the following file:
entities.hpp