FEPiCpp: ShapeFunction< Simplex< 2 > > Class Template Reference
ShapeFunction< Simplex< 2 > > Class Template Reference
#include <shapefunctions.hpp>
Public Member Functions
ShapeFunction (int degree=1, char flags=0)
void setDegree (int degree)
void setDegree (int degree, char flags)
void calculateDenomList ()
double operator() (double L1, double L2, int ith) const
double operator() (Eigen::Vector2d const &L, int ith) const
Eigen::Vector2d gradL (double L1, double L2, int ith) const
Eigen::Vector2d gradL (Eigen::Vector2d const &L, int ith)
int getDegree () const
int getNumDof () const
Public Attributes
std::vector< Eigen::Vector2i > _bar_nodes
std::vector< long int > _denom
int _degree
char _flags
int _ndof
Detailed Description
template<>
class ShapeFunction< Simplex< 2 > >
Cria funções de interpolação de Lagrange no triângulo unitário, podendo ser enriquecidos com função bolha (hierárquica ou não).
Definition at line 208 of file shapefunctions.hpp.
Constructor & Destructor Documentation
ShapeFunction< Simplex< 2 > >::ShapeFunction (int degree = 1, char flags = 0) [inline]
Parameters:
degree o grau de intepolação
flags 8 bits:
bit0 se com bolha
bit1 se com bolha hierárquica
Note:
se setar o bit1 automaticamente é setado o bit0
Definition at line 219 of file shapefunctions.hpp.
References genTriParametricPtsINT(), get_bit(), and set_bit().
                                            : _degree(degree), _flags(flags)
  {
    if (get_bit(_flags,1))
      set_bit(_flags,0);
    _ndof = (degree+1)*(degree+2)/2 + get_bit(_flags,0);
    this->_bar_nodes = genTriParametricPtsINT(degree);
    this->calculateDenomList();
  };
Member Function Documentation
void ShapeFunction< Simplex< 2 > >::calculateDenomList () [inline]
NOT FOR USERS
Definition at line 258 of file shapefunctions.hpp.
References Fepic::max().
  {
    this->_denom.resize(_bar_nodes.size());
    /* long int para evitar overflow */
    long int  denom_partF, denom_partG, denom_partH, Q0, Q1, Q2;
    // para cada ponto, calcular o denominador
    for (uint i = 0; i < _bar_nodes.size(); i++)
    {
      denom_partF = 1;
      denom_partG = 1;
      denom_partH = 1;
      Q1 = this->_bar_nodes[i][0];
      Q2 = this->_bar_nodes[i][1];
      Q0 = this->_degree-Q1-Q2;
      for (uint k = 0; k < Fepic::max(Q0, Q1, Q2); ++k)
      {
        if (k<Q0) denom_partF *= Q0 - k;
        if (k<Q1) denom_partG *= Q1 - k;
        if (k<Q2) denom_partH *= Q2 - k;
      }
      this->_denom[i] = denom_partF*denom_partG*denom_partH;
    }
  }
int ShapeFunction< Simplex< 2 > >::getDegree () const [inline]
Retorna o grau do polinômio.
Definition at line 397 of file shapefunctions.hpp.
  {
    return _degree;
  }
int ShapeFunction< Simplex< 2 > >::getNumDof () const [inline]
Retorna o número de graus de liberdade.
Definition at line 404 of file shapefunctions.hpp.
References get_bit().
    {
        return (_degree+1)*(_degree+2)/2. + get_bit(_flags,0);
    }
Eigen::Vector2d ShapeFunction< Simplex< 2 > >::gradL (Eigen::Vector2d const & L, int ith) [inline]
Definition at line 390 of file shapefunctions.hpp.
References gradL().
  {
    return this->gradL(L[0], L[1], ith);
  }
Eigen::Vector2d ShapeFunction< Simplex< 2 > >::gradL (double L1, double L2, int ith) const [inline]
Retorna o gradiente no triangulo unitário, i.e.
Definition at line 340 of file shapefunctions.hpp.
References _ddxomega(), _omega(), _prod3(), and get_bit().
  {
    if ((ith<0) || (ith>=_ndof))
    {
      std::cout << "error:ShapeFunction::gradL(): invalid index." << std::endl;
      throw;
    }
    if (_degree == 0)
      return Eigen::Vector2d(0,0);
    double L0 = 1. - L1 - L2;
    int Q1 = this->_bar_nodes[ith][0],
      Q2 = this->_bar_nodes[ith][1],
      Q0 = this->_degree-Q1-Q2,
      n  = _degree;
    Eigen::Vector2d V;
    /* função bolha */
    if (get_bit(_flags,0) && (ith==_ndof-1))
    {
      V[0] = 27.*L2*(L0-L1);
      V[1] = 27.*L1*(L0-L2);
      return V;
    }
    /* lembrete: ddL1 = -ddL0 */
    V[0] = -_ddxomega(n, Q0, L0)*_omega(n, Q1, L1)*_omega(n, Q2, L2) +
          _ddxomega(n, Q1, L1)*_omega(n, Q2, L2)*_omega(n, Q0, L0);
    /* lembrete: ddL2 = -ddL0 */
    V[1] = -_ddxomega(n, Q0, L0)*_omega(n, Q1, L1)*_omega(n, Q2, L2) +
          _ddxomega(n, Q2, L2)*_omega(n, Q1, L1)*_omega(n, Q0, L0);
    /* correção da bolha */
    if (get_bit(_flags,0) && (!get_bit(_flags,1)))
    {
      V[0] -= pow(3,3-_degree)*_prod3(_degree, Q0)*
                     _prod3(_degree, Q1)*
                   _prod3(_degree, Q2)* L2*(L0-L1);
      V[1] -= pow(3,3-_degree)*_prod3(_degree, Q0)*
                     _prod3(_degree, Q1)*
                   _prod3(_degree, Q2)* L1*(L0-L2);
    }
    return V/_denom[ith];
  }
double ShapeFunction< Simplex< 2 > >::operator() (Eigen::Vector2d const & L, int ith) const [inline]
Retorna a função avaliada nas coordenadas (L1, L2) do triângulo unitário
Definition at line 331 of file shapefunctions.hpp.
  {
    return this->operator()(L[0], L[1], ith);
  }
double ShapeFunction< Simplex< 2 > >::operator() (double L1, double L2, int ith) const [inline]
Retorna a função avaliada nas coordenadas (L1, L2) do triângulo unitário
Definition at line 290 of file shapefunctions.hpp.
References _omega(), _prod3(), and get_bit().
  {
    if ((ith<0) || (ith>=_ndof))
    {
      std::cout << "error:ShapeFunction::operator(): invalid index." << std::endl;
      throw;
    }
    if (_degree==0)
    {
      return 1.;
    }
    /* função bolha */
    if (get_bit(_flags,0) && (ith==_ndof-1))
    {
      return 27.*(1. - L1 - L2)*L1*L2;
    }
    double L0 = 1. - L1 - L2;
    int Q1 = this->_bar_nodes[ith][0],
      Q2 = this->_bar_nodes[ith][1],
      Q0 = this->_degree-Q1-Q2;
    double result = _omega(_degree, Q0, L0)*
                    _omega(_degree, Q1, L1)*
                    _omega(_degree, Q2, L2);
    /* correção da bolha */
    if (get_bit(_flags,0) && (!get_bit(_flags,1)))
    {
      result -= pow(3,3-_degree)*_prod3(_degree, Q0)*
                     _prod3(_degree, Q1)*
                     _prod3(_degree, Q2)* (L0*L1*L2);
    }
    return result / _denom[ith];
  }
void ShapeFunction< Simplex< 2 > >::setDegree (int degree) [inline]
Definition at line 228 of file shapefunctions.hpp.
References genTriParametricPtsINT(), get_bit(), and set_bit().
  {
    if (get_bit(_flags,1))
      set_bit(_flags,0);
    _ndof = (degree+1)*(degree+2)/2 + get_bit(_flags,0);
    this->_bar_nodes = genTriParametricPtsINT(degree);
    this->calculateDenomList();
        _degree = degree;
  }
void ShapeFunction< Simplex< 2 > >::setDegree (int degree, char flags) [inline]
Defini o grau de função de lagrange.
Parameters:
degree o grau
flags os flags indicando se é uma função enriquecida, etc ...
são 8 bits:
bit0 se com bolha
bit1 se com bolha hierárquica
Note:
se setar o bit1 automaticamente é setado o bit0
Definition at line 247 of file shapefunctions.hpp.
  {
    _flags = flags;
    this->setDegree(degree);
  }
Member Data Documentation
std::vector<Eigen::Vector2i> ShapeFunction< Simplex< 2 > >::_bar_nodes
Definition at line 409 of file shapefunctions.hpp.
int ShapeFunction< Simplex< 2 > >::_degree
Definition at line 411 of file shapefunctions.hpp.
std::vector<long int> ShapeFunction< Simplex< 2 > >::_denom
Definition at line 410 of file shapefunctions.hpp.
char ShapeFunction< Simplex< 2 > >::_flags
Definition at line 412 of file shapefunctions.hpp.
int ShapeFunction< Simplex< 2 > >::_ndof
Definition at line 413 of file shapefunctions.hpp.
The documentation for this class was generated from the following file:
shapefunctions.hpp