FEPiCpp: HalfEdgeLab< Traits > Class Template Reference
HalfEdgeLab< Traits > Class Template Reference
#include <halfedgelab.hpp>
Inherits HalfEdge< Traits >, and _Labelable.
Public Types
typedef Traits::MeshT MeshT
Public Member Functions
HalfEdgeLab (uint cellid, int ith, int label=0)
HalfEdgeLab ()
void propagateHalf (MeshT &mesh) const
void propagateTag (MeshT &mesh, bool force=false) const
~HalfEdgeLab ()
Detailed Description
template<class Traits>
class HalfEdgeLab< Traits >
Trata-se da classe HalfEdge com herança de classe _Labelable.
Definition at line 31 of file halfedgelab.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::MeshT HalfEdgeLab< Traits >::MeshT
Definition at line 35 of file halfedgelab.hpp.
Constructor & Destructor Documentation
template<class Traits > HalfEdgeLab< Traits >::HalfEdgeLab (uint cellid, int ith, int label = 0) [inline]
Construtor.
Parameters:
cellid O iD da célula incidente.
ith A posição da aresta nesta célula.
label o rótulo.
Definition at line 42 of file halfedgelab.hpp.
template<class Traits > HalfEdgeLab< Traits >::HalfEdgeLab () [inline]
Definition at line 43 of file halfedgelab.hpp.
template<class Traits > HalfEdgeLab< Traits >::~HalfEdgeLab () [inline]
Destrutor.
Definition at line 76 of file halfedgelab.hpp.
Member Function Documentation
template<class Traits > void HalfEdgeLab< Traits >::propagateHalf (MeshT & mesh) const [inline]
Faz com que cada nó desta HalfEdgeLab aponte para ela.
Parameters:
mesh a malha na qual a HalfEdgeLab está contida.
Definition at line 48 of file halfedgelab.hpp.
References _HalfThingCore< HalfEdge< Traits > >::getPosition().
template<class Traits > void HalfEdgeLab< Traits >::propagateTag (MeshT & mesh, bool force = false) const [inline]
Atribui o rótulo desta HalfEdgeLab a seus nós.
Parameters:
force quando true indica atribuição incondicional, quando false, a atribuição é feita somente se cada nó tem label=0;
Definition at line 61 of file halfedgelab.hpp.
References _HalfThingCore< HalfEdge< Traits > >::getPosition(), and _Labelable::getTag().
The documentation for this class was generated from the following file:
halfedgelab.hpp