FEPiCpp: Triangle< Traits > Class Template Reference
Triangle< Traits > Class Template Reference
#include <triangle.hpp>
Inherits _Poly2d< Traits >.
Classes
class iCellData
Public Types
typedef Simplex< 2 > ElmClass
typedef UndefElement VolumeT
typedef Triangle< Traits > FaceT
typedef Triangle< Traits > CellT
typedef Edge< Traits > BorderT
typedef Traits::PointT BndBorderT
typedef Edge< Traits > EdgeT
typedef Traits::PointT PointT
typedef Traits::MeshT MeshT
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
Triangle ()
Triangle (Fepic::vectorui const &nodes, int label=0)
void printSelfVtk (std::ostream &o, int order) const
void setOrder (int order)
~Triangle ()
Static Public Member Functions
static int getMshTag (int order)
static int getNumNodesCell (int order)
static int getCellTypeVtk ()
static Fepic::matrixi getEdgesLocalNodes (int order)
static Fepic::vectori getOppELN (int n)
static int getNumCellsMM (int n)
static int getNumBubbles (int n)
static std::vector
< Eigen::Vector2d > getParametricPts (int n)
Static Public Attributes
static const int n_borders = 3
static const int n_vertices = 3
Detailed Description
template<class Traits>
class Triangle< Traits >
A classe de triângulos. A dimensão de seu tipo na malha é 2, mas não se deve confundir com a dimensão do espaço onde o triângulo está, que pode ser 2 ou 3. O triângulo tem no mínimo 3 nós (um em cada vértice; triângulo linear). Um triângulo de ordem n tem (n+1)(n+2)/2 nós.
Definition at line 35 of file triangle.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::PointT Triangle< Traits >::BndBorderT
Definition at line 50 of file triangle.hpp.
template<class Traits > typedef Edge<Traits> Triangle< Traits >::BorderT
Definition at line 49 of file triangle.hpp.
template<class Traits > typedef Triangle<Traits> Triangle< Traits >::CellT
Definition at line 47 of file triangle.hpp.
template<class Traits > typedef Edge<Traits> Triangle< Traits >::EdgeT
Definition at line 52 of file triangle.hpp.
template<class Traits > typedef Simplex<2> Triangle< Traits >::ElmClass
Definition at line 41 of file triangle.hpp.
template<class Traits > typedef Triangle<Traits> Triangle< Traits >::FaceT
Reimplemented from _Poly2d< Traits >.
Definition at line 44 of file triangle.hpp.
template<class Traits > typedef Traits::MeshT Triangle< Traits >::MeshT
Reimplemented from _Poly2d< Traits >.
Definition at line 54 of file triangle.hpp.
template<class Traits > typedef Traits::PointT Triangle< Traits >::PointT
Definition at line 53 of file triangle.hpp.
template<class Traits > typedef Eigen::Matrix<double, Traits::spacedim, 1> Triangle< Traits >::VecT
Reimplemented from _Poly2d< Traits >.
Definition at line 56 of file triangle.hpp.
template<class Traits > typedef UndefElement Triangle< Traits >::VolumeT
Definition at line 43 of file triangle.hpp.
Constructor & Destructor Documentation
template<class Traits > Triangle< Traits >::Triangle () [inline]
Construtor.
Definition at line 60 of file triangle.hpp.
template<class Traits > Triangle< Traits >::Triangle (Fepic::vectorui const & nodes, int label = 0) [inline]
Construtor.
Parameters:
nodes vetor com os nós que compõe o Triangle.
Definition at line 67 of file triangle.hpp.
template<class Traits > Triangle< Traits >::~Triangle () [inline]
Destrutor.
Definition at line 278 of file triangle.hpp.
Member Function Documentation
template<class Traits > static int Triangle< Traits >::getCellTypeVtk () [inline, static]
TRABALHO: apenas linear retorna a tag do formato Vtk correspondente a este elemento.
Definition at line 120 of file triangle.hpp.
template<class Traits > static Fepic::matrixi Triangle< Traits >::getEdgesLocalNodes (int order) [inline, static]
INICIALIZADOR ... NOT FOR USERS!
Definition at line 136 of file triangle.hpp.
template<class Traits > static int Triangle< Traits >::getMshTag (int order) [inline, static]
Retorna a tag do formato Msh correspondente a um triângulo de ordem order.
Definition at line 73 of file triangle.hpp.
template<class Traits > static int Triangle< Traits >::getNumBubbles (int n) [inline, static]
Retorna o número de pontos interiores a um triângulo unitário de ordem n
Definition at line 186 of file triangle.hpp.
template<class Traits > static int Triangle< Traits >::getNumCellsMM (int n) [inline, static]
Retorna o número de mini-células de uma mini-malha de ordem n.
Definition at line 179 of file triangle.hpp.
template<class Traits > static int Triangle< Traits >::getNumNodesCell (int order) [inline, static]
Retorna o número de nós de um triângulo de ordem order
Definition at line 92 of file triangle.hpp.
template<class Traits > static Fepic::vectori Triangle< Traits >::getOppELN (int n) [inline, static]
NOT FO USERS
Parameters:
n ordem
Definition at line 162 of file triangle.hpp.
template<class Traits > static std::vector<Eigen::Vector2d> Triangle< Traits >::getParametricPts (int n) [inline, static]
Retorna as coordenadas dos pontos de um triângulo unitário de ordem n
Definition at line 193 of file triangle.hpp.
References genTriParametricPts().
template<class Traits > void Triangle< Traits >::printSelfVtk (std::ostream & o, int order) const [inline]
Imprime a célula no formate Vtk.
Note:
O número de subdivisões necessários para imprimir o triângulo é order^2
Warning:
Pula linha no final.
Definition at line 102 of file triangle.hpp.
References Triangle< Traits >::iCellData::getMinimesh(), and _Poly2d< Traits >::getNodeIdx().
template<class Traits > void Triangle< Traits >::setOrder (int order) [inline]
Atualiza a ordem deste elemento.
Warning:
Toda vez que a ordem da malha for alterada, essa função DEVE SER CHAMADA.
Definition at line 129 of file triangle.hpp.
References _Poly2d< Traits >::_node.
Member Data Documentation
template<class Traits > const int Triangle< Traits >::n_borders = 3 [static]
Reimplemented from _Poly2d< Traits >.
Definition at line 38 of file triangle.hpp.
template<class Traits > const int Triangle< Traits >::n_vertices = 3 [static]
Reimplemented from _Poly2d< Traits >.
Definition at line 39 of file triangle.hpp.
The documentation for this class was generated from the following file:
triangle.hpp