FEPiCpp: iPolyhedron< Traits > Class Template Reference
iPolyhedron< Traits > Class Template Reference
#include <ipolyhedron.hpp>
Inherits iLabelable.
Inherited by Tetrahedron< Traits >.
Public Types
typedef Traits::CellT CellT
typedef ElementProperties
< CellT, Traits >::FaceT FaceT
typedef Traits::MeshT MeshT
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
iPolyhedron ()
iPolyhedron (Fepic::vectorui const &nodes, int label=0)
iPolyhedron (Fepic::vectorui &&nodes, int label=0)
int getNumNodes () const
uint getNodeIdx (int ith) const
void setNode (int ith, uint nodeid)
iHalfFace< Traits > * getHalf (int ith)
bool isAnFace (Fepic::vectorui const &vertices, int &face, int &anchor) const
bool isAnParallelFace (Fepic::vectorui vertices, int &face, int &anchor)
void printSelfState (std::ostream &o) const
Fepic::vectorui getBorderNodes (int ith, MeshT const &mesh) const
Fepic::vectorui getBorderVertices (int ith) const
void propagateHalf (MeshT &mesh) const
void propagateLabel (MeshT &mesh, bool force=false) const
Static Public Attributes
static const int Dim = 3
static const int N_borders = ElementProperties<CellT, Traits>::N_borders
static const int N_vertices = ElementProperties<CellT, Traits>::N_vertices
Detailed Description
template<class Traits>
class iPolyhedron< Traits >
Definition at line 28 of file ipolyhedron.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::CellT iPolyhedron< Traits >::CellT
Definition at line 34 of file ipolyhedron.hpp.
template<class Traits > typedef ElementProperties<CellT, Traits>::FaceT iPolyhedron< Traits >::FaceT
Reimplemented in Tetrahedron< Traits >.
Definition at line 35 of file ipolyhedron.hpp.
template<class Traits > typedef Traits::MeshT iPolyhedron< Traits >::MeshT
Reimplemented in Tetrahedron< Traits >.
Definition at line 36 of file ipolyhedron.hpp.
template<class Traits > typedef Eigen::Matrix<double, Traits::spacedim, 1> iPolyhedron< Traits >::VecT
Reimplemented in Tetrahedron< Traits >.
Definition at line 41 of file ipolyhedron.hpp.
Constructor & Destructor Documentation
template<class Traits > iPolyhedron< Traits >::iPolyhedron () [inline]
Definition at line 43 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::N_vertices.
                : iLabelable()
  {
    _node.resize(N_vertices);
  }
template<class Traits > iPolyhedron< Traits >::iPolyhedron (Fepic::vectorui const & nodes, int label = 0) [inline]
Parameters:
nodes vetor com os nós que compõe o polígono.
Definition at line 50 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::N_vertices.
                                                       : iLabelable(label), _node(nodes)
  {
#ifdef FEPIC_DEBUG_ON
    if (_node.size() < static_cast<uint>(N_vertices))
    {
      std::cout << "error:iPolyhedron constructor: número insuficiente de nós.\n";
      throw;
    }
#endif
  }
template<class Traits > iPolyhedron< Traits >::iPolyhedron (Fepic::vectorui && nodes, int label = 0) [inline]
Parameters:
nodes vetor com os nós que compõe o polígono.
Definition at line 63 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::N_vertices.
                                                  : iLabelable(label), _node(std::move(nodes))
  {
#ifdef FEPIC_DEBUG_ON
    if (_node.size() < N_vertices)
    {
      std::cout << "error:iPolyhedron constructor: número insuficiente de nós.\n";
      throw;
    }
#endif
  }
Member Function Documentation
template<class Traits > Fepic::vectorui iPolyhedron< Traits >::getBorderNodes (int ith, MeshT const & mesh) const [inline]
Retorna um vetor com os nós da i-ésima face.
Parameters:
ith a i-ésima face.
Definition at line 184 of file ipolyhedron.hpp.
  {
    Fepic::vectorui nodes;
    for (uint i = 0, tam=mesh.faces_local_nodes[ith].size(); i < tam; i++)
      nodes.push_back( _node[ mesh.faces_local_nodes[ith][i] ] );
    return nodes;
  }
template<class Traits > Fepic::vectorui iPolyhedron< Traits >::getBorderVertices (int ith) const [inline]
Retorna um vetor com os vértices da i-ésima face
Definition at line 196 of file ipolyhedron.hpp.
  {
    static Fepic::matrixi faces_vtx(ElementProperties<CellT, Traits>::get_faces_vtx());
    uint vsize = faces_vtx[ith].size();
    Fepic::vectorui vtx(vsize);
    for (uint i = 0; i < vsize; ++i)
      vtx[i] = _node[faces_vtx[ith][i]];
    return vtx;
  }
template<class Traits > iHalfFace<Traits>* iPolyhedron< Traits >::getHalf (int ith) [inline]
Retorna a i-ésima half-edge.
Definition at line 103 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::N_borders.
  {
#ifdef FEPIC_DEBUG_ON
    if (ith >= N_borders)
    {
      std::cout << "getHalf: out of range" << std::endl;
      throw;
    }
#endif
    return &_hf[ith];
  }
template<class Traits > uint iPolyhedron< Traits >::getNodeIdx (int ith) const [inline]
Retorna o índice do i-ésimo nó do polígono.
Definition at line 81 of file ipolyhedron.hpp.
Referenced by iPolyhedron< Traits >::printSelfState(), and Tetrahedron< Traits >::printSelfVTK().
  {
#ifdef FEPIC_DEBUG_ON
    return _node.at(ith);
#else
    return _node[ith];
#endif
  }
template<class Traits > int iPolyhedron< Traits >::getNumNodes () const [inline]
Definition at line 74 of file ipolyhedron.hpp.
  {
    return _node.size();
  }
template<class Traits > bool iPolyhedron< Traits >::isAnFace (Fepic::vectorui const & vertices, int & face, int & anchor) const [inline]
Retorna se os vértices passados formam uma face nesse poliedro.
Parameters:
[in] nodes um vetor com os vértices. O tamanho do vetor deve ser exatamente o número de lados (N_borders) do elemento degenerado deste poliedro.
[out] O índice local da face.
[out] a âncora.
Returns:
true se forma uma face, false caso contrário.
Warning:
A ordem da numeração dos nós é importante!
Note:
definição para ancora: dada uma face n0,n1,...,nB, se ela é a face F e ancora A de um poliedro, então, o nó B-A é o primeiro nó da face F do poliedro.
Definition at line 125 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::N_borders.
Referenced by iPolyhedron< Traits >::isAnParallelFace().
  {
    static const Fepic::matrixi faces_vtx(ElementProperties<CellT, Traits>::get_faces_vtx());
    // CHECK
    if (int(vertices.size()) != FaceT::N_borders)
    {
      std::cout << "isAnFace error: wrong parameter!" << std::endl;
      std::cout << "vertices.size() = " << vertices.size() << std::endl;
    }
    Fepic::vectorui temp(FaceT::N_borders);
    Fepic::vectorui this_vtx(FaceT::N_borders);
    for (int f = 0; f < N_borders; ++f) // para cada face
    {
      for (int n = 0; n < FaceT::N_borders; n++)
      {
        this_vtx[n] = _node[ faces_vtx[f][n] ];
      }
      for (int a = 0; a < FaceT::N_borders; ++a) // para cada ancora
      {
        rotate_copy(vertices.begin(), vertices.begin()+a, vertices.end(), temp.begin()); // temp = rot(vertices + a);
        if(temp == this_vtx)
        {
          face = f;
          anchor = a;
          return true;
        }
      }
    }
    return false;
  }
template<class Traits > bool iPolyhedron< Traits >::isAnParallelFace (Fepic::vectorui vertices, int & face, int & anchor) [inline]
O mesmo que a função isAnFace, mas aqui a ordem dos vértices podem ser anti-paralelos a face.
Definition at line 165 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::isAnFace().
  {
    if (this->isAnFace(vertices, face, anchor))
      return true;
    reverse(vertices.begin(), vertices.end());
    return (this->isAnFace(vertices, face, anchor));
  }
template<class Traits > void iPolyhedron< Traits >::printSelfState (std::ostream & o) const [inline]
Definition at line 174 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::getNodeIdx().
  {
    o << getNodeIdx(0);
    for (uint i = 1, tam=this->_node.size(); i < tam; i++)
      o << " " << getNodeIdx(i);
  }
template<class Traits > void iPolyhedron< Traits >::propagateHalf (MeshT & mesh) const [inline]
Atribui a cada nó deste tetraedro sua respectiva half-face.
Definition at line 210 of file ipolyhedron.hpp.
References iPolyhedron< Traits >::N_borders.
  {
    for (int f = 0; f < N_borders; ++f) // loop  nas faces
      for (uint i = 0, tam=mesh.faces_local_nodes[0].size(); i < tam; ++i)
        mesh.getNode(_node[mesh.faces_local_nodes[f][i]])->setHalf(_hf[f]);
  }
template<class Traits > void iPolyhedron< Traits >::propagateLabel (MeshT & mesh, bool force = false) const [inline]
Atribui o o label do tetraedro em seus nós.
Parameters:
force Caso true, a herança do label será feita sem restrição. Caso false, a herança será feita apenas se cada nó não tiver label (i.e., label = 0).
Warning:
CONFERIR!!
Definition at line 222 of file ipolyhedron.hpp.
References iLabelable::getLabel().
  {
    if (force)
      for (int i = 0; i < this->node.size(); i++)
        mesh.getNode(_node[i])->setLabel(this->getLabel());
    else
      for (int i = 0; i < this->node.size(); i++)
        if (mesh.getNode(_node[i])->getLabel() == 0)
          mesh.getNode(_node[i])->setLabel(this->getLabel());
  }
template<class Traits > void iPolyhedron< Traits >::setNode (int ith, uint nodeid) [inline]
Defini o i-ésimo nó do polígono como nodeid
Definition at line 92 of file ipolyhedron.hpp.
  {
#ifdef FEPIC_DEBUG_ON
    _node.at(ith) = nodeid;
#else
    _node[ith] = nodeid;
#endif
  }
Member Data Documentation
template<class Traits > const int iPolyhedron< Traits >::Dim = 3 [static]
Reimplemented in Tetrahedron< Traits >.
Definition at line 31 of file ipolyhedron.hpp.
template<class Traits > const int iPolyhedron< Traits >::N_borders = ElementProperties<CellT, Traits>::N_borders [static]
Definition at line 38 of file ipolyhedron.hpp.
Referenced by iPolyhedron< Traits >::getHalf(), iPolyhedron< Traits >::isAnFace(), and iPolyhedron< Traits >::propagateHalf().
template<class Traits > const int iPolyhedron< Traits >::N_vertices = ElementProperties<CellT, Traits>::N_vertices [static]
Definition at line 39 of file ipolyhedron.hpp.
Referenced by iPolyhedron< Traits >::iPolyhedron().
The documentation for this class was generated from the following file:
ipolyhedron.hpp