FEPiCpp: iTriangle< Traits > Class Template Reference
iTriangle< Traits > Class Template Reference
#include <entities.hpp>
Inherits iPolygon< Traits >.
Classes
class iCellData
Public Types
typedef Simplex< 2 > ElmClass
typedef UndefElement VolumeT
typedef iTriangle< Traits > FaceT
typedef iTriangle< Traits > CellT
typedef iEdge< Traits > BorderT
typedef Traits::PointT BndBorderT
typedef iEdge< Traits > EdgeT
typedef Traits::PointT PointT
typedef Traits::MeshT MeshT
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
iTriangle ()
iTriangle (Fepic::vectorui const &nodes, int label=0)
void printSelfVTK (std::ostream &o, int order) const
void setOrder (int order)
~iTriangle ()
Static Public Member Functions
static int getMSHTag (int order)
static int getNumNodesCell (int order)
static int getCellTypeVTK ()
static Fepic::matrixi getEdgesLocalNodes (int order)
static Fepic::vectori getOppELN (int n)
static int getNumCellsMM (int n)
static int getNumBubbles (int n)
static std::vector
< Eigen::Vector2d > getParametricPts (int n)
Static Public Attributes
static const int N_borders = 3
static const int N_vertices = 3
Detailed Description
template<class Traits>
class iTriangle< Traits >
A classe de triângulos. A dimensão de seu tipo na malha é 2, mas não se deve confundir com a dimensão do espaço onde o triângulo está, que pode ser 2 ou 3. O triângulo tem no mínimo 3 nós (um em cada vértice; triângulo linear). Um triângulo de ordem n tem (n+1)(n+2)/2 nós.
Definition at line 1545 of file entities.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::PointT iTriangle< Traits >::BndBorderT
Definition at line 1559 of file entities.hpp.
template<class Traits > typedef iEdge<Traits> iTriangle< Traits >::BorderT
Definition at line 1558 of file entities.hpp.
template<class Traits > typedef iTriangle<Traits> iTriangle< Traits >::CellT
Definition at line 1556 of file entities.hpp.
template<class Traits > typedef iEdge<Traits> iTriangle< Traits >::EdgeT
Definition at line 1561 of file entities.hpp.
template<class Traits > typedef Simplex<2> iTriangle< Traits >::ElmClass
Definition at line 1551 of file entities.hpp.
template<class Traits > typedef iTriangle<Traits> iTriangle< Traits >::FaceT
Reimplemented from iPolygon< Traits >.
Definition at line 1554 of file entities.hpp.
template<class Traits > typedef Traits::MeshT iTriangle< Traits >::MeshT
Reimplemented from iPolygon< Traits >.
Definition at line 1563 of file entities.hpp.
template<class Traits > typedef Traits::PointT iTriangle< Traits >::PointT
Definition at line 1562 of file entities.hpp.
template<class Traits > typedef Eigen::Matrix<double, Traits::spacedim, 1> iTriangle< Traits >::VecT
Reimplemented from iPolygon< Traits >.
Definition at line 1565 of file entities.hpp.
template<class Traits > typedef UndefElement iTriangle< Traits >::VolumeT
Definition at line 1553 of file entities.hpp.
Constructor & Destructor Documentation
template<class Traits > iTriangle< Traits >::iTriangle () [inline]
Construtor.
Definition at line 1569 of file entities.hpp.
                    : iPolygon<Traits>()
        {
        }
template<class Traits > iTriangle< Traits >::iTriangle (Fepic::vectorui const & nodes, int label = 0) [inline]
Construtor.
Parameters:
nodes vetor com os nós que compõe o iTriangle.
Definition at line 1576 of file entities.hpp.
                                                           : iPolygon<Traits>(nodes, label)
        {
        }
template<class Traits > iTriangle< Traits >::~iTriangle () [inline]
Destrutor.
Definition at line 1791 of file entities.hpp.
{}
Member Function Documentation
template<class Traits > static int iTriangle< Traits >::getCellTypeVTK () [inline, static]
TRABALHO: apenas linear retorna a tag do formato VTK correspondente a este elemento.
Definition at line 1628 of file entities.hpp.
        {
                return 5; // VTK_TRIANGLE(=5)
        }
template<class Traits > static Fepic::matrixi iTriangle< Traits >::getEdgesLocalNodes (int order) [inline, static]
INICIALIZADOR ... NOT FOR USERS!
Definition at line 1644 of file entities.hpp.
        {
                /* Essa função é usada para atualizar o vetor edges_local_nodes
                 * que tem no imesh. Esse vetor contém a numeração local dos nós de
                 * uma dada ordem.
                 */
                const int E = order - 1;
                Fepic::matrixi en(3, Fepic::vectori(order + 1));
                for (int i = 0; i < 3; i++)
                {
                        en[i][0] = i;
                        en[i][1] = (i+1)%3;
                        for (int j = 0; j < E; ++j)
{
                                en[i][j+2] = 3+i*E + j;
                        }
                }
                return en;
        }
template<class Traits > static int iTriangle< Traits >::getMSHTag (int order) [inline, static]
Retorna a tag do formato MSH correspondente a um triângulo de ordem order.
Definition at line 1582 of file entities.hpp.
        {
                switch (order)
                {
                        case 1: return MSH_TRI_3;
                        case 2: return MSH_TRI_6;
                        case 3: return MSH_TRI_10; // TRABALHO, muito TRABALHO
                        case 4: return MSH_TRI_15;
                        case 5: return MSH_TRI_21;
                        default:
                                std::cout << "Triangle order not supported." << std::endl;
                                throw;
                }
        }
template<class Traits > static int iTriangle< Traits >::getNumBubbles (int n) [inline, static]
Retorna o número de pontos interiores a um triângulo unitário de ordem n
Definition at line 1697 of file entities.hpp.
    {
        return (n-1)*(n-2)/2;
    }
template<class Traits > static int iTriangle< Traits >::getNumCellsMM (int n) [inline, static]
Retorna o número de mini-células de uma mini-malha de ordem n.
Definition at line 1690 of file entities.hpp.
    {
        return n*n;
    }
template<class Traits > static int iTriangle< Traits >::getNumNodesCell (int order) [inline, static]
Retorna o número de nós de um triângulo de ordem order
Definition at line 1599 of file entities.hpp.
        {
                return (order+1)*(order+2)/2;
        }
template<class Traits > static Fepic::vectori iTriangle< Traits >::getOppELN (int n) [inline, static]
NOT FO USERS
Parameters:
n ordem
Definition at line 1673 of file entities.hpp.
    {
        Fepic::vectori opp_eln(n+1);
        opp_eln[0]=1;
        opp_eln[n]=0;
        for (int i = 0; i < n-1; ++i)
        {
            opp_eln[i+1] = n-i;
        }
        return opp_eln;
    }
template<class Traits > static std::vector<Eigen::Vector2d> iTriangle< Traits >::getParametricPts (int n) [inline, static]
Retorna as coordenadas dos pontos de um triângulo unitário de ordem n
Definition at line 1704 of file entities.hpp.
References genTriParametricPts().
    {
        return genTriParametricPts(n);
    }
template<class Traits > void iTriangle< Traits >::printSelfVTK (std::ostream & o, int order) const [inline]
Imprime a célula no formate VTK.
Note:
O número de subdivisões necessários para imprimir o triângulo é order^2
Warning:
Pula linha no final.
Definition at line 1609 of file entities.hpp.
References iTriangle< Traits >::iCellData::getMinimesh(), and iPolygon< Traits >::getNodeIdx().
        {
        static iCellData  data;
        Fepic::matrixi      minimesh;
        minimesh = data.getMinimesh(order);
        o <<"3 "<<  this->getNodeIdx(minimesh[0][0]) << " " << this->getNodeIdx(minimesh[0][1]) << " " << this->getNodeIdx(minimesh[0][2]);
        for (uint i = 1, tam=minimesh.size(); i < tam; ++i)
        {
            o << std::endl;
            o <<"3 "<<  this->getNodeIdx(minimesh[i][0]) << " " << this->getNodeIdx(minimesh[i][1]) << " " << this->getNodeIdx(minimesh[i][2]);
        }
        }
template<class Traits > void iTriangle< Traits >::setOrder (int order) [inline]
Atualiza a ordem deste elemento.
Warning:
Toda vez que a ordem da malha for alterada, essa função DEVE SER CHAMADA.
Definition at line 1637 of file entities.hpp.
References iPolygon< Traits >::_node.
        {
                this->_node.resize((order+1)*(order+2)/2);
        }
Member Data Documentation
template<class Traits > const int iTriangle< Traits >::N_borders = 3 [static]
Reimplemented from iPolygon< Traits >.
Definition at line 1548 of file entities.hpp.
template<class Traits > const int iTriangle< Traits >::N_vertices = 3 [static]
Reimplemented from iPolygon< Traits >.
Definition at line 1549 of file entities.hpp.
The documentation for this class was generated from the following file:
entities.hpp