FEPiCpp: iMesh< Traits > Class Template Reference
iMesh< Traits > Class Template Reference
#include <imesh.hpp>
Public Types
typedef Traits::CellT CellT
typedef VolumeDef< CellT::Dim,
CellT >::VolumeT VolumeT
typedef FaceDef< CellT::Dim,
CellT >::FaceT FaceT
typedef Edge< Traits > EdgeT
typedef Traits::PointT PointT
typedef CellT::BorderT CellBT
typedef CellT::BndBorderT BndCellBT
typedef HalfDef< CellT::Dim,
Traits >::HalfT HalfT
typedef HalflDef< CellT::Dim,
Traits >::HalflT HalflT
typedef HalfEdge< Traits > HalfEdgeLabT
typedef HalfFace< Traits > HalfFaceLabT
typedef HalfEdgeLab< Traits > HalflEdgeLabT
typedef HalfFaceLab< Traits > HalflFaceLabT
typedef std::deque< CellT > CellList
typedef std::deque< PointT > PointList
typedef std::deque< HalflT > HalflList
typedef CellList::iterator CellIterator
typedef PointList::iterator PointIterator
typedef HalflList::iterator HalflIterator
typedef CellList::const_iterator CellConstIterator
typedef PointList::const_iterator PointConstIterator
typedef HalflList::const_iterator HalflConstIterator
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
iMesh ()
iMesh (iMesh const &)
~iMesh ()
void setFamilyFiles ()
void readFileMsh (const char *filename)
void readMarkedElementsMsh4edge (std::ifstream &File)
void readMarkedElementsMsh4face (std::ifstream &File)
void readMarkedElementsMsh4volume (std::ifstream &File)
void buildAdjacency4face ()
void buildAdjacency4volume ()
void writeFileState ()
void writeVtk (bool flinear=false)
template<class T >
void addScalarVtk (const char *nome_var, T &&scalar, uint num_pts)
template<class T >
void addVectorVtk (const char *nome_var, T &&arrayos, int dim, uint num_pts)
void addPointTagVtk (const char *nome_var)
void addPointHalfVtk (const char *nome_var)
void printInfo (std::ostream &o=std::cout) const
void setOrder (int order)
void remodelCellsNodes4face (int n)
void remodelCellsNodes4volume (int n)
bool theseVerticesFormAHalfl (Fepic::vectorui const &vtx, uint &half_id, bool dead_mh=false)
PointT * getNode (uint nth)
const PointT * getNode (uint nth) const
HalflT * getHalfl (uint nth)
const HalflT * getHalfl (uint nth) const
CellT * getCell (uint nth)
const CellT * getCell (uint nth) const
void getCellCoords (Eigen::MatrixXd &X, Eigen::VectorXi const &map)
uint addCell (CellT const &C)
uint addPoint (PointT const &P)
uint addHalfl (HalflT const &h)
uint getNumCells () const
uint getNumCellsTotal () const
uint getNumNodes () const
uint getNumNodesTotal () const
uint getNumHalfls () const
uint getNumHalflTotal () const
double getPerimeter ()
int getOrder () const
CellIterator cellBegin ()
CellIterator cellEnd ()
PointIterator pointBegin ()
PointIterator pointEnd ()
HalflIterator mhalfBegin ()
HalflIterator mhalfEnd ()
std::string getBaseName () const
Public Attributes
Fepic::matrixi edges_local_nodes
Fepic::matrixi faces_local_nodes
Fepic::vectori opp_eln
Fepic::matrixi opp_fln
CellList _cellL
PointList _pointL
HalflList _mhalfL
Detailed Description
template<class Traits>
class iMesh< Traits >
Definition at line 31 of file imesh.hpp.
Member Typedef Documentation
template<class Traits> typedef CellT::BndBorderT iMesh< Traits >::BndCellBT
Definition at line 41 of file imesh.hpp.
template<class Traits> typedef CellT::BorderT iMesh< Traits >::CellBT
Definition at line 40 of file imesh.hpp.
template<class Traits> typedef CellList::const_iterator iMesh< Traits >::CellConstIterator
Definition at line 58 of file imesh.hpp.
template<class Traits> typedef CellList::iterator iMesh< Traits >::CellIterator
Definition at line 54 of file imesh.hpp.
template<class Traits> typedef std::deque<CellT> iMesh< Traits >::CellList
Definition at line 50 of file imesh.hpp.
template<class Traits> typedef Traits::CellT iMesh< Traits >::CellT
Definition at line 34 of file imesh.hpp.
template<class Traits> typedef Edge<Traits> iMesh< Traits >::EdgeT
Definition at line 38 of file imesh.hpp.
template<class Traits> typedef FaceDef<CellT::Dim, CellT>::FaceT iMesh< Traits >::FaceT
Definition at line 36 of file imesh.hpp.
template<class Traits> typedef HalfEdge<Traits> iMesh< Traits >::HalfEdgeLabT
Definition at line 45 of file imesh.hpp.
template<class Traits> typedef HalfFace<Traits> iMesh< Traits >::HalfFaceLabT
Definition at line 46 of file imesh.hpp.
template<class Traits> typedef HalflList::const_iterator iMesh< Traits >::HalflConstIterator
Definition at line 60 of file imesh.hpp.
template<class Traits> typedef HalfEdgeLab<Traits> iMesh< Traits >::HalflEdgeLabT
Definition at line 47 of file imesh.hpp.
template<class Traits> typedef HalfFaceLab<Traits> iMesh< Traits >::HalflFaceLabT
Definition at line 48 of file imesh.hpp.
template<class Traits> typedef HalflList::iterator iMesh< Traits >::HalflIterator
Definition at line 56 of file imesh.hpp.
template<class Traits> typedef std::deque<HalflT> iMesh< Traits >::HalflList
Definition at line 52 of file imesh.hpp.
template<class Traits> typedef HalflDef<CellT::Dim, Traits>::HalflT iMesh< Traits >::HalflT
Definition at line 44 of file imesh.hpp.
template<class Traits> typedef HalfDef<CellT::Dim, Traits>::HalfT iMesh< Traits >::HalfT
Definition at line 43 of file imesh.hpp.
template<class Traits> typedef PointList::const_iterator iMesh< Traits >::PointConstIterator
Definition at line 59 of file imesh.hpp.
template<class Traits> typedef PointList::iterator iMesh< Traits >::PointIterator
Definition at line 55 of file imesh.hpp.
template<class Traits> typedef std::deque<PointT> iMesh< Traits >::PointList
Definition at line 51 of file imesh.hpp.
template<class Traits> typedef Traits::PointT iMesh< Traits >::PointT
Definition at line 39 of file imesh.hpp.
template<class Traits> typedef Eigen::Matrix<double, Traits::spacedim, 1> iMesh< Traits >::VecT
Definition at line 62 of file imesh.hpp.
template<class Traits> typedef VolumeDef<CellT::Dim, CellT>::VolumeT iMesh< Traits >::VolumeT
Definition at line 35 of file imesh.hpp.
Constructor & Destructor Documentation
template<class Traits> iMesh< Traits >::iMesh () [inline]
Definition at line 65 of file imesh.hpp.
  {
    _is_family=0;
    _add_scalar_vtk_n_calls=0;
    _add_vector_vtk_n_calls=0;
    _order = 1;
    _MeshMethods<iMesh<Traits>, CellT::Dim>::buildCellLocalNodes(*this);
  };
template<class Traits> iMesh< Traits >::iMesh (iMesh< Traits > const &)
template<class Traits> iMesh< Traits >::~iMesh ()
Member Function Documentation
template<class Traits> uint iMesh< Traits >::addCell (CellT const & C) [inline]
Adiciona uma célula e retorna seu id.
Definition at line 238 of file imesh.hpp.
References iMesh< Traits >::_cellL.
Referenced by iMesh< Traits >::readFileMsh().
  {
    if (_dead_cells.empty())
    {
      _cellL.push_back(C);
      return _cellL.size()-1;
    }
    else
    {
      uint id = _dead_cells.back();
      _cellL.at(id) = C;
      _dead_cells.pop_back();
      return id;
    }
  }
template<class Traits> uint iMesh< Traits >::addHalfl (HalflT const & h) [inline]
Adiciona uma half-xxxx
Parameters:
h A half-xxxx a ser adicionada.
Returns:
A posição da half-xxxx na lista
Definition at line 276 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
Referenced by iMesh< Traits >::buildAdjacency4face(), and iMesh< Traits >::buildAdjacency4volume().
  {
    if (_dead_mhalf.empty())
    {
      _mhalfL.push_back(h);
      return _mhalfL.size()-1;
    }
    else
    {
      uint id = _dead_mhalf.back();
      _mhalfL.at(id) = h;
      _dead_mhalf.pop_back();
      return id;
    }
  }
template<class Traits> uint iMesh< Traits >::addPoint (PointT const & P) [inline]
Adiciona um ponto e retorna seu id.
Definition at line 256 of file imesh.hpp.
References iMesh< Traits >::_pointL.
  {
    if (_dead_points.empty())
    {
      _pointL.push_back(P);
      return _pointL.size()-1;
    }
    else
    {
      uint id = _dead_points.back();
      _pointL.at(id) = P;
      _dead_points.pop_back();
      return id;
    }
  }
template<class Traits > void iMesh< Traits >::addPointHalfVtk (const char * nome_var = "node labels")
Definition at line 847 of file imeshIO.hpp.
References iMesh< Traits >::getNode(), and iMesh< Traits >::getNumNodes().
{
  std::stringstream ss;
  uint num_pts = this->getNumNodes();
  if (_is_family)
  {
    ss << (this->_basename) << std::setfill('0') << std::setw(5);
    ss << _family-1 << ".vtk";
  }
  else
  {
    ss << (this->_basename) << ".vtk";
  }
  std::ofstream Fout;
  Fout.open( ss.str().data(), std::ios::app);
  Fout << std::setprecision(8);
  Fout << std::setiosflags(std::ios::showpoint);
  if (_add_scalar_vtk_n_calls==0)
  {
    Fout << "POINT_DATA " << num_pts << std::endl;
    Fout << std::endl;
  }
  _add_scalar_vtk_n_calls++;
  Fout << "SCALARS " << nome_var << " int"   << std::endl;
  Fout << "LOOKUP_TABLE default"            << std::endl;
  for (uint i=0; i<num_pts; ++i) {
    Fout << (this->getNode(i)->getHalf()->getIncidCell()) << std::endl;
  };
  Fout << std::endl << std::endl;
  Fout.close();
};
template<class Traits > void iMesh< Traits >::addPointTagVtk (const char * nome_var = "node labels")
Definition at line 804 of file imeshIO.hpp.
References iMesh< Traits >::getNode(), and iMesh< Traits >::getNumNodes().
{
  std::stringstream ss;
  uint num_pts = this->getNumNodes();
  if (_is_family)
  {
    ss << (this->_basename) << std::setfill('0') << std::setw(5);
    ss << _family-1 << ".vtk";
  }
  else
  {
    ss << (this->_basename) << ".vtk";
  }
  std::ofstream Fout;
  Fout.open( ss.str().data(), std::ios::app);
  Fout << std::setprecision(8);
  Fout << std::setiosflags(std::ios::showpoint);
  if (_add_scalar_vtk_n_calls==0)
  {
    Fout << "POINT_DATA " << num_pts << std::endl;
    Fout << std::endl;
  }
  _add_scalar_vtk_n_calls++;
  Fout << "SCALARS " << nome_var << " int"   << std::endl;
  Fout << "LOOKUP_TABLE default"            << std::endl;
  for (uint i=0; i<num_pts; ++i) {
    Fout << (getNode(i)->getTag()) << std::endl;
  };
  Fout << std::endl << std::endl;
  Fout.close();
};
template<class Traits > template<class T > void iMesh< Traits >::addScalarVtk (const char * nome_var, T && scalar, uint num_pts)
T: qualquer objeto chamável
Definition at line 763 of file imeshIO.hpp.
{
  std::stringstream ss;
  if (_is_family)
  {
    ss << (this->_basename) << std::setfill('0') << std::setw(5);
    ss << _family-1 << ".vtk";
  }
  else
  {
    ss << (this->_basename) << ".vtk";
  }
  std::ofstream Fout;
  Fout.open( ss.str().data(), std::ios::app);
  Fout << std::setprecision(8);
  Fout << std::setiosflags(std::ios::showpoint);
  if (_add_scalar_vtk_n_calls==0)
  {
    Fout << "POINT_DATA " << num_pts << std::endl;
    Fout << std::endl;
  }
  _add_scalar_vtk_n_calls++;
  Fout << "SCALARS " << nome_var << " float"   << std::endl;
  Fout << "LOOKUP_TABLE default"            << std::endl;
  for (uint i=0; i<num_pts; ++i)
    Fout << scalar[i] << std::endl;
  Fout << std::endl << std::endl;
  Fout.close();
};
template<class Traits> template<class T > void iMesh< Traits >::addVectorVtk (const char * nome_var, T && arrayos, int dim, uint num_pts)
template<class Traits > void iMesh< Traits >::buildAdjacency4face ()
Uma vez já lida uma tabela de conectividade, i.e., as células e seus nós, a função abaixo constrói as relações de adjacências (half-edfe, half-face) ou nenhum se a célula for aresta.
Note:
células mortas não são cosideradas.
Definition at line 52 of file imeshIO.hpp.
References iMesh< Traits >::_cellL, iMesh< Traits >::addHalfl(), and iMesh< Traits >::getCell().
Referenced by _MeshMethods< Mesh, 2 >::buildAdjacency().
{
  int n_borders = CellT::n_borders;
  Fepic::vectorui edge_vtx(2);
  Fepic::vectorui cell_ith(2);
  std::map<Fepic::vectorui, Fepic::vectorui> table; // Key: (n0, n1) ... atributos (elemento, ith)
  std::map<Fepic::vectorui, Fepic::vectorui>::iterator tab_it, tab_it2;
  CellIterator cell = iMesh::_cellL.begin();
  uint otherC, otherith, thisC, thisith;
  int thislabel;
  uint k=0;
  for (auto cellend=_cellL.end(); cell != cellend ; ++cell)
  {
    if (!cell->disabled())
    {
      for (int ith = 0; ith < n_borders; ++ith)
      {
        edge_vtx = cell->getBorderVertices(ith);
        cell_ith[0] = k;
        cell_ith[1] = ith;
        table.insert(std::pair<Fepic::vectorui, Fepic::vectorui>(edge_vtx, cell_ith));
      }
    }
    ++k;
  }
  while (!table.empty())
  {
    tab_it = --table.end();
    reverse_copy(tab_it->first.begin(), tab_it->first.end(), edge_vtx.begin());
    tab_it2 = table.find(edge_vtx);
    if (tab_it2 != table.end()) // se econtrou uma edge em comum
    {
      otherC = tab_it2->second[0];
      otherith = tab_it2->second[1];
      thisC = tab_it->second[0];
      thisith =  tab_it->second[1];
      this->getCell(thisC)->getHalf(thisith)->setCompleteID(otherC, otherith);
      this->getCell(otherC)->getHalf(otherith)->setCompleteID(thisC, thisith);
      table.erase(tab_it2);
      table.erase(tab_it);
    }
    else
    {
      thisC = tab_it->second[0];
      thisith =  tab_it->second[1];
      thislabel = this->getCell(thisC)->getTag();
      HalflEdgeLabT temp(thisC, thisith, thislabel);
      uint mHE_universal_iD = addHalfl(temp);
      this->getCell(thisC)->getHalf(thisith)->setCompleteID(mHE_universal_iD, -1);
      table.erase(tab_it);
    }
  }
}
template<class Traits > void iMesh< Traits >::buildAdjacency4volume ()
Note:
células mortas não são consideradas.
Definition at line 118 of file imeshIO.hpp.
References iMesh< Traits >::_cellL, iMesh< Traits >::addHalfl(), and iMesh< Traits >::getCell().
Referenced by _MeshMethods< Mesh, 3 >::buildAdjacency().
{
  //const int n_borders = CellT::n_borders;
  //const int n_anch    = FaceT::n_borders;
    //typedef std::pair<std::array<uint, n_anch>, std::array<uint, 2> > PairT; // < (vértices da face) , (elemento, ith) >
    //typedef std::unordered_map<std::array<uint, n_anch>, std::array<uint, 2> >  MapT;
  //std::array<uint, n_anch>  face_vtx;
  //std::array<uint, 2>       cell_ith;
  //MapT                      table; // < (vértices da face) , (elemento, ith) >
  //auto                      tab_it = table.begin(), tab_it2 = table.begin();  // iterators
  //CellIterator              cell = this->_cellL.begin();
  //uint                      otherC, otherith, thisC, thisith;
  //int                       thislabel;
    //int                       a, k=0;
    //bool                      found;
  //for (auto cellend=_cellL.end(); cell != cellend ; ++cell)
  //{
    //if (!cell->disabled())
    //{
      //for (int ith = 0; ith < n_borders; ++ith)
      //{
                //copy_from(cell->getBorderVertices(ith).begin(), face_vtx.begin(), face_vtx.end());
        //cell_ith[0] = k;
        //cell_ith[1] = ith;
        //table.insert(PairT(face_vtx, cell_ith));
      //}
    //}
    //++k;
  //}
  //while (!table.empty())
  //{
        //tab_it = table.begin();
    //reverse_copy(tab_it->first.begin(), tab_it->first.end(), face_vtx.begin());
    //found = false;
    //for (a = 0; a != n_anch; ++a) // ancora
    //{
      //tab_it2 = table.find(face_vtx);
      //if (tab_it2 != table.end()) // se econtrou uma face em comum
      //{
        //otherC = tab_it2->second[0];
        //otherith = tab_it2->second[1];
        //thisC = tab_it->second[0];
        //thisith =  tab_it->second[1];
        //this->getCell(thisC)->getHalf(thisith)->setCompleteID(otherC, otherith, a);
        //this->getCell(otherC)->getHalf(otherith)->setCompleteID(thisC, thisith, a);
        //table.erase(tab_it2);
        //table.erase(tab_it);
        //found = true;
        //break;
      //}
      //rotate(face_vtx.begin(), face_vtx.begin()+1, face_vtx.end());
    //}
    //if(!found)
    //{
      //thisC = tab_it->second[0];
      //thisith =  tab_it->second[1];
      //thislabel = this->getCell(thisC)->getTag();
      //HalflFaceLabT temp(thisC, thisith, 0, thislabel);
      //uint mHE_universal_iD = addHalfl(temp);
      //this->getCell(thisC)->getHalf(thisith)->setCompleteID(mHE_universal_iD, -1, 0);
      //table.erase(tab_it);
    //}
  //}
  const int n_borders = CellT::n_borders;
  const int n_anch    = FaceT::n_borders;
  typedef std::pair<Fepic::vectorui, Fepic::vectorui>   PairT; // < (vértices da face) , (elemento, ith) >
  typedef std::map<Fepic::vectorui, Fepic::vectorui>  MapT;
  Fepic::vectorui face_vtx(FaceT::n_borders);
  Fepic::vectorui cell_ith(2);
  MapT            table; // < (nós da face) , (elemento, ith) >
  MapT::iterator  tab_it, tab_it2;
  CellIterator    cell = this->_cellL.begin();
  uint            otherC, otherith, thisC, thisith;
  int             thislabel;
  int             a;
  uint k=0;
  for (auto cellend=_cellL.end(); cell != cellend ; ++cell)
  {
    if (!cell->disabled())
    {
      for (int ith = 0; ith != n_borders; ++ith)
      {
        face_vtx = std::move( cell->getBorderVertices(ith) );
        cell_ith[0] = k;
        cell_ith[1] = ith;
        table.insert(std::make_pair(face_vtx, cell_ith));
      }
    }
    ++k;
  }
  bool found;
  while (!table.empty())
  {
    tab_it = table.begin();
    reverse_copy(tab_it->first.begin(), tab_it->first.end(), face_vtx.begin());
    found = false;
    for (a = 0; a != n_anch; ++a) // ancora
    {
      tab_it2 = table.find(face_vtx);
      if (tab_it2 != table.end()) // se econtrou uma face em comum
      {
        otherC = tab_it2->second[0];
        otherith = tab_it2->second[1];
        thisC = tab_it->second[0];
        thisith =  tab_it->second[1];
        _cellL[thisC].getHalf(thisith)->setCompleteID(otherC, otherith, a);
        _cellL[otherC].getHalf(otherith)->setCompleteID(thisC, thisith, a);
        table.erase(tab_it2);
        table.erase(tab_it);
        found = true;
        break;
      }
      rotate(face_vtx.begin(), face_vtx.begin()+1, face_vtx.end());
    }
    if(!found)
    {
      thisC = tab_it->second[0];
      thisith =  tab_it->second[1];
      thislabel = this->getCell(thisC)->getTag();
      HalflFaceLabT temp(thisC, thisith, 0, thislabel);
      uint mHE_universal_iD = addHalfl(temp);
      this->getCell(thisC)->getHalf(thisith)->setCompleteID(mHE_universal_iD, -1, 0);
      table.erase(tab_it);
    }
  }
}
template<class Traits> CellIterator iMesh< Traits >::cellBegin () [inline]
Retorna um iterador apontando para o começo da lista de células.
Definition at line 364 of file imesh.hpp.
References iMesh< Traits >::_cellL.
  {
    return _cellL.begin();
  }
template<class Traits> CellIterator iMesh< Traits >::cellEnd () [inline]
Retorna um iterador apontando para o depois-do-final da lista de células.
Definition at line 371 of file imesh.hpp.
References iMesh< Traits >::_cellL.
  {
    return _cellL.end();
  }
template<class Traits> std::string iMesh< Traits >::getBaseName () const [inline]
Retorna o nome base. O nome base é o nome do arquivo passado para o iMesh, sem extensão.
Definition at line 406 of file imesh.hpp.
  {
    return _basename;
  }
template<class Traits> CellT* iMesh< Traits >::getCell (uint nth) [inline]
Retorna a n-ésima celula (adivinha o tipo de célula pelo tipo da malha)
Definition at line 214 of file imesh.hpp.
References iMesh< Traits >::_cellL.
Referenced by iMesh< Traits >::buildAdjacency4face(), iMesh< Traits >::buildAdjacency4volume(), and iMesh< Traits >::writeFileState().
  {
    return &_cellL[nth];
  }
template<class Traits> const CellT* iMesh< Traits >::getCell (uint nth) const [inline]
Definition at line 219 of file imesh.hpp.
References iMesh< Traits >::_cellL.
  {
    return &_cellL[nth];
  }
template<class Traits> void iMesh< Traits >::getCellCoords (Eigen::MatrixXd & X, Eigen::VectorXi const & map) [inline]
Retorna na matriz X as coordenadas dos nós passados em map. As colunas de X correspondem a dimensão enquanto as linhas correspondem aos graus de liberdade.
Definition at line 228 of file imesh.hpp.
References iMesh< Traits >::getNode().
  {
    X.resize(map.size(), Traits::spacedim);
    for (int n = 0; n < map.size(); ++n)
      X.row(n) = this->getNode(map(n))->getCoord().transpose();
  }
template<class Traits> HalflT* iMesh< Traits >::getHalfl (uint nth) [inline]
Retorna a n-ésima mhalf-edge/face (adivinha pelo tipo da malha)
Definition at line 201 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
Referenced by iMesh< Traits >::readFileMsh(), iMesh< Traits >::theseVerticesFormAHalfl(), and iMesh< Traits >::writeFileState().
  {
    return &_mhalfL[nth];
  }
template<class Traits> const HalflT* iMesh< Traits >::getHalfl (uint nth) const [inline]
Definition at line 206 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
  {
    return &_mhalfL[nth];
  }
template<class Traits> PointT* iMesh< Traits >::getNode (uint nth) [inline]
Retorna o n-ésimo nó da malha.
Definition at line 189 of file imesh.hpp.
References iMesh< Traits >::_pointL.
Referenced by iMesh< Traits >::addPointHalfVtk(), iMesh< Traits >::addPointTagVtk(), iMesh< Traits >::getCellCoords(), iMesh< Traits >::readFileMsh(), and iMesh< Traits >::writeFileState().
  {
    return &_pointL[nth];
  }
template<class Traits> const PointT* iMesh< Traits >::getNode (uint nth) const [inline]
Definition at line 194 of file imesh.hpp.
References iMesh< Traits >::_pointL.
  {
    return &_pointL[nth];
  }
template<class Traits> uint iMesh< Traits >::getNumCells () const [inline]
Retorna o número células
Note:
não conta com o/a(s) marcado/a(s) como killed.
Definition at line 295 of file imesh.hpp.
References iMesh< Traits >::_cellL.
Referenced by iMesh< Traits >::printInfo(), iMesh< Traits >::writeFileState(), and iMesh< Traits >::writeVtk().
  {
    return _cellL.size() - _dead_cells.size();
  }
template<class Traits> uint iMesh< Traits >::getNumCellsTotal () const [inline]
Retorna o número de células.
Note:
incluindo o/a(s) marcado/a(s) como killed.
Definition at line 303 of file imesh.hpp.
References iMesh< Traits >::_cellL.
{
    return _cellL.size();
  }
template<class Traits> uint iMesh< Traits >::getNumHalfls () const [inline]
Retorna número de mhalfs.
Note:
não conta com o/a(s) marcado/a(s) como killed.
Definition at line 325 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
Referenced by iMesh< Traits >::printInfo().
  {
    return _mhalfL.size() - _dead_mhalf.size();
  }
template<class Traits> uint iMesh< Traits >::getNumHalflTotal () const [inline]
Retorna o número de mhalfs.
Note:
incluindo o/a(s) marcado/a(s) como killed.
Definition at line 333 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
Referenced by iMesh< Traits >::theseVerticesFormAHalfl(), and iMesh< Traits >::writeFileState().
  {
    return _mhalfL.size();
  }
template<class Traits> uint iMesh< Traits >::getNumNodes () const [inline]
Retorna o número de nós.
Note:
não conta com o/a(s) marcado/a(s) como killed.
Definition at line 310 of file imesh.hpp.
References iMesh< Traits >::_pointL.
Referenced by iMesh< Traits >::addPointHalfVtk(), iMesh< Traits >::addPointTagVtk(), iMesh< Traits >::printInfo(), and iMesh< Traits >::readFileMsh().
  {
    return _pointL.size() - _dead_points.size();
  }
template<class Traits> uint iMesh< Traits >::getNumNodesTotal () const [inline]
Retorna no número de nós.
Note:
incluindo o/a(s) marcado/a(s) como killed.
Definition at line 318 of file imesh.hpp.
References iMesh< Traits >::_pointL.
Referenced by iMesh< Traits >::writeFileState().
{
    return _pointL.size();
  }
template<class Traits> int iMesh< Traits >::getOrder () const [inline]
Retorna a ordem da malha.
Definition at line 357 of file imesh.hpp.
Referenced by _MeshMethods< Mesh, 3 >::buildCellLocalNodes(), and _MeshMethods< Mesh, 2 >::buildCellLocalNodes().
  {
    return _order;
  }
template<class Traits> double iMesh< Traits >::getPerimeter () [inline]
apenas para 2D ainda. retorna o comprimento do contorno.
Definition at line 341 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
  {
    auto it = _mhalfL.begin();
    Fepic::vectorui vtx;
    double sum=0.;
    std::cout << _mhalfL.size() << std::endl;
    for (; it!= _mhalfL.end(); ++it)
      sum += it->HalfT::getLenght(*this);
    return sum;
  }
template<class Traits> HalflIterator iMesh< Traits >::mhalfBegin () [inline]
Retorna um iterador apontando para o começo da lista de mhalfs.
Definition at line 392 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
  {
    return _mhalfL.begin();
  }
template<class Traits> HalflIterator iMesh< Traits >::mhalfEnd () [inline]
Retorna um iterador apontando para o depois-do-final da lista de mhalfs.
Definition at line 399 of file imesh.hpp.
References iMesh< Traits >::_mhalfL.
  {
    return _mhalfL.end();
  }
template<class Traits> PointIterator iMesh< Traits >::pointBegin () [inline]
Retorna um iterador apontando para o começo da lista de pontos.
Definition at line 378 of file imesh.hpp.
References iMesh< Traits >::_pointL.
  {
    return _pointL.begin();
  }
template<class Traits> PointIterator iMesh< Traits >::pointEnd () [inline]
Retorna um iterador apontando para o depois-do-final da lista de pontos.
Definition at line 385 of file imesh.hpp.
References iMesh< Traits >::_pointL.
  {
    return _pointL.end();
  }
template<class Traits> void iMesh< Traits >::printInfo (std::ostream & o = std::cout) const [inline]
Imprime algumas informações da malha.
Definition at line 112 of file imesh.hpp.
References iMesh< Traits >::getNumCells(), iMesh< Traits >::getNumHalfls(), and iMesh< Traits >::getNumNodes().
  {
    std::cout << "mesh file: " << _meshfile << std::endl;
    std::cout << "cell type: " << CellT::name() << std::endl;
    std::cout << "order:     " << this->_order << std::endl;
    std::cout << "# nodes:   " << getNumNodes() << std::endl;
    std::cout << "# cells:   " << getNumCells() << std::endl;
    std::cout << "# mhalfs:  " << getNumHalfls() << std::endl;
  }
template<class Traits > void iMesh< Traits >::readFileMsh (const char * filename)
Lê a malha de um arquivo no formato .msh. A ordem da malha é detectada altomaticamente.
Definition at line 269 of file imeshIO.hpp.
References iMesh< Traits >::_cellL, iMesh< Traits >::_mhalfL, iMesh< Traits >::_pointL, iMesh< Traits >::addCell(), iMesh< Traits >::getHalfl(), Edge< Traits >::getMshTag(), iMesh< Traits >::getNode(), iMesh< Traits >::getNumNodes(), search_word(), iMesh< Traits >::setOrder(), and iMesh< Traits >::theseVerticesFormAHalfl().
{
  /*
   * O que é feito:
   *
   * 1) primeiramente lê-se apenas as células (conectividade clássica);
   * 2) depois são construídos as half-edges e(ou) half-faces, lendo-se
   *    os elementos de dimensões menores.
   *
   * */
  std::ifstream File(filename);
  if (File.fail()) {
    std::cout << "I can't read the file "<< filename << " ... " << std::endl;
    throw;
  };
  _meshfile = filename;
  int _final = _meshfile.find(".msh");
  _basename = _meshfile.substr(0,_final);
  double    coord[3];
  int     type_aux;
  char    lixo[256];
  size_t    NODE_POS;  // $Nodes
  size_t    ELEM_POS;  // $Elements
  // nós
  NODE_POS = search_word(File, "$Nodes");
  NODE_POS++;  // only to avoid gcc warning: variable ‘NODE_POS’ set but not used [-Wunused-but-set-variable]
  uint num_pts;
  File >> num_pts;
  _pointL.resize(num_pts);
  for (uint i=0; i< getNumNodes(); ++i) {
    File >> lixo;  // nº do nó
    File >> coord[0];
    File >> coord[1];
    File >> coord[2];
    _pointL[i].setCoord(coord);
  }
  // os pontos não estão completas: falta atribuir os labels
  // contagem de elementos e alocação
  ELEM_POS = search_word(File, "$Elements");
  uint num_cells=0;
  uint num_elms;
  File >> num_elms;
  /* ---------------------------------------
   * Detectando a ordem da malha
   * --------------------------------------- */
  for (uint k = 0; k < num_elms; ++k)
  {
    File >> lixo; // numero do elemento
    File >> type_aux;
    int elm_dim = getDimForElementTypeMsh(type_aux);
    if (elm_dim == CellT::Dim)
    {
      this->setOrder( getOrderForElementTypeMsh(type_aux) );
      break;
    }
    File.getline(lixo, 256);
  }
  int order = this->_order;
  CellT   Cell;
  /* --------------------------------------
   * Lendo as células
   * -------------------------------------- */
  File.seekg(ELEM_POS);
  File >> num_elms;
  Cell.setOrder(order);
  uint id_aux;
  int  num_tags;
  int  label_aux;
  uint counter; // contagem para verificação de erros.
  for (uint k=0; k < num_elms; ++k)
  {
    File >> counter; // numero do elemento .. verificação de sincronia
    if (counter != k+1)
    {
      std::cout << filename <<  ": invalid file format!" << std::endl;
      throw;
    }
    File >> type_aux;
    int elm_dim = getDimForElementTypeMsh(type_aux);
    File >> num_tags;
    File >> label_aux;
    for (int j=0; j<num_tags-1; ++j)
    {
      File >> lixo;
    }
    switch (elm_dim)
    {
      case 0: // caso ponto
        File >> id_aux;
        --id_aux;
        this->getNode(id_aux)->setTag(label_aux);
        break;
      case 1: // caso aresta
        {
          if (std::is_same<EdgeT, CellT>::value)
          {
            if (CellT::getMshTag(order) != type_aux)
            {
              std::cout << "Invalid edge! file has: " << getElementNameMsh(type_aux) << std::endl;
              std::cout << "But Mesh is configured to support: "
                                      << getElementNameMsh(EdgeT::getMshTag(order)) << std::endl;
              throw;
            }
            for (int i=0; i<Cell.getNumNodes(); ++i)
            {
              uint nodeid;
              File >> nodeid;
              --nodeid;
              Cell.setNode(i, nodeid);
            }
            Cell.setTag(label_aux);
            this->addCell(Cell);
            ++num_cells;
          }
          else
            File.getline(lixo, 256);
        }
        break;
      case 2: // caso face
        {
          if (std::is_same<FaceT, CellT>::value)
          {
            if (CellT::getMshTag(order) != type_aux)
            {
              std::cout << "Invalid face! file has: " << getElementNameMsh(type_aux) << std::endl;
              std::cout << "But Mesh is configured to support: "
                                      << getElementNameMsh(FaceT::getMshTag(order)) << std::endl;
              throw;
            }
            for (int i=0; i<Cell.getNumNodes(); ++i)
            {
              uint nodeid;
              File >> nodeid;
              --nodeid;
              Cell.setNode(i, nodeid);
            }
            Cell.setTag(label_aux);
            this->addCell(Cell);
            ++num_cells;
          }
          else
            File.getline(lixo, 256);
        }
        break;
      case 3: // caso volume
        {
          if (std::is_same<VolumeT, CellT>::value)
          {
            if (CellT::getMshTag(order) != type_aux)
            {
              std::cout << "Invalid volume! file has: " << getElementNameMsh(type_aux) << std::endl;
              std::cout << "But Mesh is configured to support: "
                                      << getElementNameMsh(FaceT::getMshTag(order)) << std::endl;
              throw;
            }
            for (int i=0; i<Cell.getNumNodes(); ++i)
            {
              uint nodeid;
              File >> nodeid;
              --nodeid;
              Cell.setNode(i, nodeid);
            }
            Cell.setTag(label_aux);
            this->addCell(Cell);
            ++num_cells;
          }
          else
            File.getline(lixo, 256);
        }
        break;
      default:
        std::cout << "invalid element ...\n";
        throw;
    }
  }
  if (num_cells == 0)
    std::cout << "WARNING: mesh file don't have any "
              << getElementNameMsh(CellT::getMshTag(order)) << std::endl;
  /* até aqui, apenas foi lido a conectividade
   */
  /* constroi as halfs e Mhalfs */
  _MeshMethods<iMesh<Traits>, CellT::Dim>::buildAdjacency(*this);
  /*
  ___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|__
  _|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___| */
  /* Procura por elementos no contorno que coincidam com as halfs. Quando encontrados,
   * os labels são propagados para as respectivas half que por sua vez propagam os
   * labels para seus nós. Os labels só são propagados se eles não foram definidos
   * nos nós anteriormente.
   */
  File.seekg(ELEM_POS);
  File >> num_elms;
  for (uint k=0; k < num_elms; ++k)
  {
    File >> counter; // numero do elemento
    if (counter != k+1)
    {
      std::cout << filename <<  ": invalid file format!" << std::endl;
      throw;
    }
    File >> type_aux;
    int elm_dim = getDimForElementTypeMsh(type_aux);
    File >> num_tags;
    File >> label_aux;
    for (int j=0; j<num_tags-1; ++j)
    {
      File >> lixo;
    }
    uint id_aux;
    switch (elm_dim) {
      case 0: // caso ponto
        File >> id_aux;
        break;
      case 1: // caso aresta
        if (std::is_same<EdgeT, CellBT>::value)
        {
          Fepic::vectorui nodes(CellBT::getNumNodesCell(order));
          Fepic::vectorui vtx(2);
          uint half_id;
          for (int i=0; i<CellBT::getNumNodesCell(order); ++i)
          {
            File >> nodes[i];
            --nodes[i];
            if (this->getNode(nodes[i])->getTag() == 0)
              this->getNode(nodes[i])->setTag(label_aux);
          }
          copy( nodes.begin(), nodes.begin()+2, vtx.begin() );
          if( this->theseVerticesFormAHalfl(vtx, half_id) )
            this->getHalfl(half_id)->setTag(label_aux);
        }
        else
        {
          uint nodeid;
          for (int i=0; i<getNumVerticesForElementTypeMsh(type_aux); ++i)
          {
            File >> nodeid;
            --nodeid;
            if (this->getNode(nodeid)->getTag() == 0)
              this->getNode(nodeid)->setTag(label_aux);
          }
        }
        break;
      case 2: // caso face
        if (std::is_same<FaceT, CellBT>::value)
        {
          Fepic::vectorui nodes(CellBT::getNumNodesCell(order));
          Fepic::vectorui vtx(CellBT::n_borders);
          uint half_id=0;
          for (int i=0; i<CellBT::getNumNodesCell(order); ++i)
          {
            File >> nodes[i];
            --nodes[i];
            if (this->getNode(nodes[i])->getTag() == 0)
              this->getNode(nodes[i])->setTag(label_aux);
          }
          copy( nodes.begin(), nodes.begin()+CellBT::n_borders, vtx.begin() );
          if( this->theseVerticesFormAHalfl(vtx, half_id) )
            this->getHalfl(half_id)->setTag(label_aux); //std::cout << (++TESTE) << std::endl;
        }
        else
        {
          uint nodeid;
          for (int i=0; i<getNumVerticesForElementTypeMsh(type_aux); ++i)
          {
            File >> nodeid;
            --nodeid;
            if ((this->getNode(nodeid)->getTag()) == 0)
              this->getNode(nodeid)->setTag(label_aux);
          }
        }
        break;
      case 3: // caso volume
        uint nodeid;
        for (int i=0; i<getNumVerticesForElementTypeMsh(type_aux); ++i)
        {
          File >> nodeid;
          --nodeid;
          if (this->getNode(nodeid)->getTag() == 0)
            this->getNode(nodeid)->setTag(label_aux);
        }
        break;
      default:
        std::cout << "invalid element ...\n";
    }
  }
  for (CellIterator cit = _cellL.begin(), cellend=_cellL.end() ; cit != cellend; ++cit)
    if (!cit->disabled())
      cit->propagateHalf(*this);
  for (HalflIterator hit= _mhalfL.begin(), hend=_mhalfL.end(); hit != hend; ++hit)
    if (!hit->disabled())
      hit->propagateHalf(*this);
  File.close();
}
template<class Traits> void iMesh< Traits >::readMarkedElementsMsh4edge (std::ifstream & File)
template<class Traits> void iMesh< Traits >::readMarkedElementsMsh4face (std::ifstream & File)
template<class Traits> void iMesh< Traits >::readMarkedElementsMsh4volume (std::ifstream & File)
template<class Traits> void iMesh< Traits >::remodelCellsNodes4face (int n) [inline]
NOT FOR USERS Depois de mudada a ordem de cada célula da malha e atualizada a matriz que contém a numeração local dos nós celulares, chama-se esta função. Ela (re)cria os nós que são compartilhados entre as células.
Definition at line 147 of file imesh.hpp.
Referenced by _MeshMethods< Mesh, 2 >::remodelCellsNodes().
  {
  } // end remodelCellsNodes4face()
template<class Traits> void iMesh< Traits >::remodelCellsNodes4volume (int n) [inline]
NOT FOR USERS Depois de mudada a ordem da malha, chama-se esta função. Ela recria os nós e determina suas posições.
Definition at line 156 of file imesh.hpp.
Referenced by _MeshMethods< Mesh, 3 >::remodelCellsNodes().
  {
  }
template<class Traits> void iMesh< Traits >::setFamilyFiles () [inline]
Definition at line 81 of file imesh.hpp.
  {
    _is_family=true;
  }
template<class Traits> void iMesh< Traits >::setOrder (int order) [inline]
Altera a ordem da malha.
Parameters:
order a nova ordem da malha
Warning:
NÂO TERMINADO
Definition at line 126 of file imesh.hpp.
References iMesh< Traits >::_cellL.
Referenced by iMesh< Traits >::readFileMsh().
  {
    if ((_order != order) && (order>0))
    {
      _order = order;
      for (auto it= _cellL.begin(), cend=_cellL.end(); it != cend; ++it)
        it->setOrder(_order);
      /* atualiando a matriz que contém a numeração dos nós locais da célula */
      _MeshMethods<iMesh<Traits>, CellT::Dim>::buildCellLocalNodes(*this);
      /* (re)cria os nós que são compartilhados entre as células. */
      _MeshMethods<iMesh<Traits>, CellT::Dim>::remodelCellsNodes(*this, order);
    }
  }
template<class Traits> bool iMesh< Traits >::theseVerticesFormAHalfl (Fepic::vectorui const & vtx, uint & half_id, bool dead_mh = false) [inline]
Verifica se os nós passados formam alguma Mhalf já existente.
Parameters:
[in] nodes os nós.
[out] id o id da Mhalf.
[in] dead_mh bool indicando se as Mhalf (dead) incluem na pesquisa.
Note:
o critério de existência é se os nós são ciclicamente iguais aos da Mhalf.
Definition at line 167 of file imesh.hpp.
References iMesh< Traits >::getHalfl(), and iMesh< Traits >::getNumHalflTotal().
Referenced by iMesh< Traits >::readFileMsh().
  {
    // OTIMIZAR
    bool RET=false;
    uint nummhalf = getNumHalflTotal();
    // IMPLEMENTAR ITERADOR
    for(uint i=0; i<nummhalf; ++i)
    {
      bool b = this->getHalfl(i)->hasTheseVertices(vtx, *this);
      if(b && (dead_mh || (!getHalfl(i)->disabled())) )
      {
        half_id = i;
        RET = true;
      }
    }
    return RET;
  }
template<class Traits > void iMesh< Traits >::writeFileState ()
Definition at line 616 of file imeshIO.hpp.
References iMesh< Traits >::getCell(), iMesh< Traits >::getHalfl(), iMesh< Traits >::getNode(), iMesh< Traits >::getNumCells(), iMesh< Traits >::getNumHalflTotal(), and iMesh< Traits >::getNumNodesTotal().
{
  int order = this->_order;
  std::ofstream Fout( (_basename + ".state").data() );
  Fout << "BASENAME: " << _basename << std::endl << std::endl;
  Fout << "NODES " << getNumNodesTotal() << std::endl;
  Fout << std::left << std::setw(22) << "x" << std::setw(22) << "y" << std::setw(22) << "z  label" << std::endl << std::endl;
  Fout.precision(15);
  for (uint k=0, tam=getNumNodesTotal(); k< tam; ++k)
  {
    this->getNode(k)->printSelfVtk(Fout);
    Fout << " " << this->getNode(k)->getTag() << std::endl;
  }
  CellT *cell;
  Fout << std::endl;
  Fout << getElementNameMsh(CellT::getMshTag(order)) << std::endl;
  for (uint i = 0; i < this->getNumCells(); i++)
  {
    cell = this->getCell(i);
    cell->printSelfState(Fout); Fout << " label:" << cell->getTag();
    Fout << std::endl;
  }
  // print Halfs
  Fout << std::endl << HalfT::getName() << std::endl;
  for (uint i = 0, tam=this->getNumCells(); i < tam; i++)
  {
    cell = this->getCell(i);
    HalfT *h_obj = cell->getHalf(0);
    for (int j = 1; j < CellT::n_borders; j++)
    {
      h_obj->printSelf(Fout);
      Fout << " | ";
      h_obj = cell->getHalf(j);
    }
    h_obj->printSelf(Fout);
    Fout << std::endl;
  }
  Fout << std::endl << "Marked " << HalfT::getName() << " " << this->getNumHalflTotal() << std::endl;
  Fout << "CELL  POSIT  (ANC)  LABEL\n";
  for (uint i = 0, tam=this->getNumHalflTotal(); i < tam; i++)
  {
    HalflT *h_obj = this->getHalfl(i);
    h_obj->printSelf(Fout); Fout << " " << h_obj->getTag();
    Fout << std::endl;
  }
  Fout << std::endl << std::endl;
  Fout.close();
}
template<class Traits > void iMesh< Traits >::writeVtk (bool flinear = false)
Imprime os pontos e células no arquivo vtk.
Parameters:
flinear se true, força a malha ser impressa como linear, se false (default), a malha é impressa da ordem que ela é.
ESTA DESCRIÇÃO PRECISA SER MELHORADA
Definition at line 685 of file imeshIO.hpp.
References iMesh< Traits >::_cellL, iMesh< Traits >::_pointL, and iMesh< Traits >::getNumCells().
{
  /*
  *
  * NOTA: TODOS os pontos são impressos. APENAS AS CÉLULAS VIVAS
  * são impressas.
  */
  int  order  = flinear ? 1 : this->_order;
  int  nc_mm  = CellT::getNumCellsMM(order);    // num de mini-células por mini-malha
  uint ncells = this->getNumCells() * nc_mm;
  std::stringstream ss;
    this->_add_scalar_vtk_n_calls=0;
    this->_add_vector_vtk_n_calls=0;
  if (this->_basename.size()==0)
    _basename="untitled";
  if (_is_family)
  {
    ss << (this->_basename) << std::setfill('0') << std::setw(5);
    ss << _family << ".vtk";
    ++_family;
  }
  else
    ss << (this->_basename) << ".vtk";
  std::ofstream Fout( ss.str().data() );
  Fout << "# vtk DataFile Version 2.0" << std::endl
       << "unstructured grid" << std::endl
       << "ASCII" << std::endl
       << "DATASET UNSTRUCTURED_GRID" << std::endl
       << "POINTS " << _pointL.size() << " float" << std::endl;
  /* imprimindo pontos */
  PointIterator pit = _pointL.begin();
  for (auto pend=_pointL.end(); pit != pend ; ++pit)
  {
    pit->printSelfVtk(Fout);
    Fout << std::endl;
  }
  /* imprimindo células */
  Fout << std::endl;
  Fout << "CELLS " << ncells << " " << ncells*(1+CellT::n_vertices) << std::endl;
  CellIterator cit = _cellL.begin();
  for (auto cellend=_cellL.end(); cit != cellend ; ++cit)
  {
    if(!cit->disabled())
    {
      cit->printSelfVtk(Fout, order);
      Fout << std::endl;
    }
  }
    int type = CellT::getCellTypeVtk();
  Fout << std::endl; cit = _cellL.begin();
  Fout << "CELL_TYPES " << ncells << std::endl;
  for (auto cellend=_cellL.end(); cit != cellend ; ++cit)
  {
    if(!cit->disabled())
    {
      for (int i = 0; i < nc_mm; i++)
        Fout << type << std::endl;
    }
  }
  Fout << std::endl;
  Fout.close();
}
Member Data Documentation
template<class Traits> CellList iMesh< Traits >::_cellL
Definition at line 420 of file imesh.hpp.
Referenced by iMesh< Traits >::addCell(), iMesh< Traits >::buildAdjacency4face(), iMesh< Traits >::buildAdjacency4volume(), iMesh< Traits >::cellBegin(), iMesh< Traits >::cellEnd(), iMesh< Traits >::getCell(), iMesh< Traits >::getNumCells(), iMesh< Traits >::getNumCellsTotal(), iMesh< Traits >::readFileMsh(), iMesh< Traits >::setOrder(), and iMesh< Traits >::writeVtk().
template<class Traits> HalflList iMesh< Traits >::_mhalfL
Definition at line 422 of file imesh.hpp.
Referenced by iMesh< Traits >::addHalfl(), iMesh< Traits >::getHalfl(), iMesh< Traits >::getNumHalfls(), iMesh< Traits >::getNumHalflTotal(), iMesh< Traits >::getPerimeter(), iMesh< Traits >::mhalfBegin(), iMesh< Traits >::mhalfEnd(), and iMesh< Traits >::readFileMsh().
template<class Traits> PointList iMesh< Traits >::_pointL
Definition at line 421 of file imesh.hpp.
Referenced by iMesh< Traits >::addPoint(), iMesh< Traits >::getNode(), iMesh< Traits >::getNumNodes(), iMesh< Traits >::getNumNodesTotal(), iMesh< Traits >::pointBegin(), iMesh< Traits >::pointEnd(), iMesh< Traits >::readFileMsh(), and iMesh< Traits >::writeVtk().
template<class Traits> Fepic::matrixi iMesh< Traits >::edges_local_nodes
Definition at line 413 of file imesh.hpp.
Referenced by _MeshMethods< Mesh, 3 >::buildCellLocalNodes(), and _MeshMethods< Mesh, 2 >::buildCellLocalNodes().
template<class Traits> Fepic::matrixi iMesh< Traits >::faces_local_nodes
Definition at line 414 of file imesh.hpp.
Referenced by _MeshMethods< Mesh, 3 >::buildCellLocalNodes().
template<class Traits> Fepic::vectori iMesh< Traits >::opp_eln
Definition at line 415 of file imesh.hpp.
template<class Traits> Fepic::matrixi iMesh< Traits >::opp_fln
Definition at line 416 of file imesh.hpp.
The documentation for this class was generated from the following files:
imesh.hpp
imeshIO.hpp