FEPiCpp: iTetrahedron< Traits > Class Template Reference
iTetrahedron< Traits > Class Template Reference
#include <entities.hpp>
Inherits iPolyhedron< Traits >.
Classes
class iCellData
Public Types
typedef Simplex< 3 > ElmClass
typedef iTetrahedron< Traits > VolumeT
typedef iTriangle< Traits > FaceT
typedef FaceT BorderT
typedef iEdge< Traits > BndBorderT
typedef BndBorderT EdgeT
typedef Traits::PointT PointT
typedef Traits::MeshT MeshT
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
iTetrahedron ()
iTetrahedron (Fepic::vectorui const &nodes, int label=0)
iTetrahedron (Fepic::vectorui &&nodes, int label=0)
void printSelfVTK (std::ostream &o, int order) const
void setOrder (int order)
Static Public Member Functions
static int getNumNodesCell (int order)
static int getCellTypeVTK ()
static int getMSHTag (int order)
static Fepic::matrixi getEdgesLocalNodes (int order)
static Fepic::matrixi getFacesLocalNodes (int order)
static Fepic::vectori getOppELN (int n)
static Fepic::matrixi getOppFLN (int n)
static int getNumCellsMM (int n)
static std::string name ()
Static Public Attributes
static const int Dim = 3
Detailed Description
template<class Traits>
class iTetrahedron< Traits >
Definition at line 2040 of file entities.hpp.
Member Typedef Documentation
template<class Traits > typedef iEdge<Traits> iTetrahedron< Traits >::BndBorderT
Definition at line 2049 of file entities.hpp.
template<class Traits > typedef FaceT iTetrahedron< Traits >::BorderT
Definition at line 2048 of file entities.hpp.
template<class Traits > typedef BndBorderT iTetrahedron< Traits >::EdgeT
Definition at line 2051 of file entities.hpp.
template<class Traits > typedef Simplex<3> iTetrahedron< Traits >::ElmClass
Definition at line 2044 of file entities.hpp.
template<class Traits > typedef iTriangle<Traits> iTetrahedron< Traits >::FaceT
Reimplemented from iPolyhedron< Traits >.
Definition at line 2047 of file entities.hpp.
template<class Traits > typedef Traits::MeshT iTetrahedron< Traits >::MeshT
Reimplemented from iPolyhedron< Traits >.
Definition at line 2053 of file entities.hpp.
template<class Traits > typedef Traits::PointT iTetrahedron< Traits >::PointT
Definition at line 2052 of file entities.hpp.
template<class Traits > typedef Eigen::Matrix<double, Traits::spacedim, 1> iTetrahedron< Traits >::VecT
Reimplemented from iPolyhedron< Traits >.
Definition at line 2055 of file entities.hpp.
template<class Traits > typedef iTetrahedron<Traits> iTetrahedron< Traits >::VolumeT
Definition at line 2046 of file entities.hpp.
Constructor & Destructor Documentation
template<class Traits > iTetrahedron< Traits >::iTetrahedron () [inline]
Definition at line 2057 of file entities.hpp.
                       : iPolyhedron<Traits>()
        {
        }
template<class Traits > iTetrahedron< Traits >::iTetrahedron (Fepic::vectorui const & nodes, int label = 0) [inline]
Parameters:
nodes vetor com os nós que compõe o polígono.
Definition at line 2063 of file entities.hpp.
                                                              : iPolyhedron<Traits>(nodes, label)
        {
        }
template<class Traits > iTetrahedron< Traits >::iTetrahedron (Fepic::vectorui && nodes, int label = 0) [inline]
Parameters:
nodes vetor com os nós que compõe o polígono.
Definition at line 2069 of file entities.hpp.
                                                          : iPolyhedron<Traits>(nodes, label)
        {
        }
Member Function Documentation
template<class Traits > static int iTetrahedron< Traits >::getCellTypeVTK () [inline, static]
Definition at line 2098 of file entities.hpp.
        {
                return 10; // VTK_TETRA (=10)
        }
template<class Traits > static Fepic::matrixi iTetrahedron< Traits >::getEdgesLocalNodes (int order) [inline, static]
INICIALIZADOR ... NÃO UTILIZAR
Definition at line 2129 of file entities.hpp.
Referenced by iTetrahedron< Traits >::getFacesLocalNodes().
        {
        static Fepic::matrixi edges_vtx = ElementProperties<iTetrahedron, Traits>::get_edges_vtx();
                const int E = order - 1;
                Fepic::matrixi en(6, std::vector<int>(order + 1));
                for (int i = 0; i < 6; i++)
                {
                        for (int j = 0; j < 2; ++j)
{
                                en[i][j] = edges_vtx[i][j];
                        }
                        for (int j = 0; j < E; ++j)
{
                                en[i][j+2] = 4 + i*E + j;
                        }
                }
                return en;
        }
template<class Traits > static Fepic::matrixi iTetrahedron< Traits >::getFacesLocalNodes (int order) [inline, static]
INICIALIZADOR ... NÃO UTILIZAR
Definition at line 2156 of file entities.hpp.
References iTetrahedron< Traits >::getEdgesLocalNodes().
        {
        static Fepic::matrixi faces_vtx(ElementProperties<iTetrahedron, Traits>::get_faces_vtx());
                const int E = order - 1;
                const int C = 4 + E*6;
                const int F = (order-1)*(order-2)/2;
                Fepic::matrixi fn(4, Fepic::vectori((order+1)*(order+2)/2));
                Fepic::matrixi ed_nds = iTetrahedron::getEdgesLocalNodes(order);
                for (int i = 0; i < 4; i++)
                {
                        for (int j = 0; j < 3; j++)
{
                                fn[i][j] = faces_vtx[i][j];
                        }
                }
                /*
                 *  face | edges         (" - ": orientação invertida)
                 * ¯¯¯¯¯¯|¯¯¯¯¯¯¯¯¯¯¯¯
                 *        0  | -0 -2 -1
                 *        1  | +0 -5 +3
                 *        2  | +4 +2 -3
                 *        3  | -4 +5 +1
                 */
                for (int i = 0; i < E; i++)
                {
                        fn[0][i+3]     = ed_nds[0][order - i];
                        fn[0][i+3+E]   = ed_nds[2][order - i];
                        fn[0][i+3+2*E] = ed_nds[1][order - i];
                        fn[1][i+3]     = ed_nds[0][2+i];
                        fn[1][i+3+E]   = ed_nds[5][order - i];
                        fn[1][i+3+2*E] = ed_nds[3][2+i];
                        fn[2][i+3]     = ed_nds[4][2+i];
                        fn[2][i+3+E]   = ed_nds[2][2+i];
                        fn[2][i+3+2*E] = ed_nds[3][order - i];
                        fn[3][i+3]     = ed_nds[4][order - i];
                        fn[3][i+3+E]   = ed_nds[5][2+i];
                        fn[3][i+3+2*E] = ed_nds[1][2+i];
                }
                for (int f = 0; f < 4; f++)
                {
                        for (int i = 0; i < F; i++)
{
                                fn[f][i+3*(1+E)] = C+f*F + i;
                        }
                }
                return fn;
        }
template<class Traits > static int iTetrahedron< Traits >::getMSHTag (int order) [inline, static]
Definition at line 2103 of file entities.hpp.
        {
                switch (order)
                {
                        case 1: return MSH_TET_4;
                        case 2: return MSH_TET_10;
                        case 3: return MSH_TET_20;
                        case 4: return MSH_TET_35;
                        case 5: return MSH_TET_56;
                        default:
                                std::cout << "invalid tetrahedron order." << std::endl;
                                throw;
                }
        }
template<class Traits > static int iTetrahedron< Traits >::getNumCellsMM (int n) [inline, static]
Retorna o número de mini-células de uma mini-malha de ordem n.
Definition at line 2310 of file entities.hpp.
    {
        return n*n*n;
    }
template<class Traits > static int iTetrahedron< Traits >::getNumNodesCell (int order) [inline, static]
Retorna o número de nós desse poliedro.
Definition at line 2075 of file entities.hpp.
        {
                return (order+1)*(order+2)*(order+3)/6;;
        }
template<class Traits > static Fepic::vectori iTetrahedron< Traits >::getOppELN (int n) [inline, static]
NOT FOR USERS
Parameters:
n ordem
Definition at line 2220 of file entities.hpp.
    {
        Fepic::vectori opp_eln(n+1);
        opp_eln[0]=1;
        opp_eln[n]=0;
        for (int i = 0; i < n-1; ++i)
        {
            opp_eln[i+1] = n-i;
        }
        return opp_eln;
    }
template<class Traits > static Fepic::matrixi iTetrahedron< Traits >::getOppFLN (int n) [inline, static]
NOT FOR USERS
getOppFLN(n)[anchor] = vetor com a visão da face oposta de âncora anchor.
Parameters:
n ordem
Definition at line 2239 of file entities.hpp.
References genTriParametricPtsINT().
    {
        int                                 k, anch;
        const int                           N = (n+1)*(n+2)/2;
        Fepic::matrixi                        opp_fln(3, Fepic::vectori(N));
        const std::vector<Eigen::Vector2i>  Coords = genTriParametricPtsINT(n);
        std::map<int, Eigen::Vector2i>      X;
        Eigen::Matrix2i A;
        Eigen::Vector2i b;
#define PAIR std::pair<int, Eigen::Vector2i>
/* transformações são feitas fazendo A*x + b */
#define DO_TRANSFORMATION_AND_APPLY for (int i = 0; i != N; ++i)                                             \
                                    {                                                                        \
                                        X[i] = A*Coords[i] + b;                                              \
                                    }                                                                        \
                                                                                                             \
                                    for (int i = 0; i != N; ++i)                                             \
                                    {                                                                        \
                                        k = find_if(X.begin(), X.end(), [i, &Coords](PAIR const& p)->bool {  \
                                                return (p.second==Coords[i]);                                \
                                            })->first;                                                       \
                                                                                                             \
                                        opp_fln[anch][i] = k;                                                \
                                    }
        /* ----------------
         *    ANCORA 0
         * ---------------- */
        anch = 0;
        A << +1, +0,
             -1, -1;
        b << +0,
             +n;
        DO_TRANSFORMATION_AND_APPLY;
        /* ----------------
         *    ANCORA 1
         * ---------------- */
        anch = 1;
        A << -1, -1,
             +0, +1;
        b << +n,
             +0;
        DO_TRANSFORMATION_AND_APPLY;
        /* ----------------
         *    ANCORA 0
         * ---------------- */
        anch = 2;
        A << +0, +1,
             +1, +0;
        b << +0,
             +0;
        DO_TRANSFORMATION_AND_APPLY;
#undef DO_TRANSFORMATION_AND_APPLY
#undef PAIR
        return opp_fln;
    }
template<class Traits > static std::string iTetrahedron< Traits >::name () [inline, static]
Definition at line 2458 of file entities.hpp.
    {
        return "Tetrahedron";
    }
template<class Traits > void iTetrahedron< Traits >::printSelfVTK (std::ostream & o, int order) const [inline]
Definition at line 2080 of file entities.hpp.
References iTetrahedron< Traits >::iCellData::getMinimesh(), and iPolygon< Traits >::getNodeIdx().
        {
        static iCellData  data;
        Fepic::matrixi      minimesh;
        minimesh = data.getMinimesh(order);
        o <<"4 "<<  this->getNodeIdx(minimesh[0][0]) << " " << this->getNodeIdx(minimesh[0][1]) << " " << this->getNodeIdx(minimesh[0][2]) << " " << this->getNodeIdx(minimesh[0][3]);
        for (uint i = 1, tam=minimesh.size(); i < tam; ++i)
        {
            o << std::endl;
            o <<"4 "<<  this->getNodeIdx(minimesh[i][0]) << " " << this->getNodeIdx(minimesh[i][1]) << " " << this->getNodeIdx(minimesh[i][2]) << " " << this->getNodeIdx(minimesh[i][3]);
        }
        }
template<class Traits > void iTetrahedron< Traits >::setOrder (int order) [inline]
Warning:
Toda vez que a ordem da malha for alterada, essa função DEVE SER CHAMADA.
Definition at line 2121 of file entities.hpp.
References iPolygon< Traits >::_node.
        {
                this->_node.resize((order+1)*(order+2)*(order+3)/6);
        }
Member Data Documentation
template<class Traits > const int iTetrahedron< Traits >::Dim = 3 [static]
Reimplemented from iPolyhedron< Traits >.
Definition at line 2042 of file entities.hpp.
The documentation for this class was generated from the following file:
entities.hpp