FEPiCpp: ShapeFunction< Simplex< 3 > > Class Template Reference
ShapeFunction< Simplex< 3 > > Class Template Reference
#include <shapefunctions.hpp>
Public Member Functions
ShapeFunction (int degree=1, char flags=0)
void setDegree (int degree)
void setDegree (int degree, char flags)
void calculateDenomList ()
double operator() (double L1, double L2, double L3, int ith) const
double operator() (Eigen::Vector3d const &L, int ith) const
Eigen::Vector3d gradL (double L1, double L2, double L3, int ith) const
Eigen::Vector3d gradL (Eigen::Vector3d const &L, int ith)
int getDegree () const
int getNumDof () const
Public Attributes
std::vector< Eigen::Vector3i > _bar_nodes
std::vector< long int > _denom
int _degree
char _flags
int _ndof
Detailed Description
template<>
class ShapeFunction< Simplex< 3 > >
Cria funções de interpolação de Lagrange no tetraedro unitário, podendo ser enriquecidos com função bolha (hierárquica ou não).
Definition at line 439 of file shapefunctions.hpp.
Constructor & Destructor Documentation
ShapeFunction< Simplex< 3 > >::ShapeFunction (int degree = 1, char flags = 0) [inline]
Parameters:
degree o grau de intepolação
flags 8 bits:
bit0 se com bolha
bit1 se com bolha hierárquica
Note:
se setar o bit1 automaticamente é setado o bit0
Definition at line 450 of file shapefunctions.hpp.
References genTetParametricPtsINT(), get_bit(), and set_bit().
                                            : _degree(degree), _flags(flags)
  {
    if (get_bit(_flags,1))
      set_bit(_flags,0);
    _ndof = (degree+1)*(degree+2)*(degree+3)/6 + get_bit(_flags,0);
    this->_bar_nodes = genTetParametricPtsINT(degree);
    this->calculateDenomList();
  };
Member Function Documentation
void ShapeFunction< Simplex< 3 > >::calculateDenomList () [inline]
NOT FOR USERS
Definition at line 489 of file shapefunctions.hpp.
References Fepic::max().
  {
    this->_denom.resize(_bar_nodes.size());
    long int  denom_partF, denom_partG, denom_partH, denom_partI, Q0, Q1, Q2, Q3;
    // para cada ponto, calcular o denominador
    for (uint i = 0; i < _bar_nodes.size(); i++)
    {
      denom_partF = 1;
      denom_partG = 1;
      denom_partH = 1;
      denom_partI = 1;
      Q1 = this->_bar_nodes[i][0];
      Q2 = this->_bar_nodes[i][1];
      Q3 = this->_bar_nodes[i][2];
      Q0 = this->_degree-Q1-Q2-Q3;
      for (uint k = 0; k < Fepic::max(Q0,Q1,Q2,Q3); ++k)
      {
        if (k<Q0) denom_partF *= Q0 - k;
        if (k<Q1) denom_partG *= Q1 - k;
        if (k<Q2) denom_partH *= Q2 - k;
        if (k<Q3) denom_partI *= Q3 - k;
      }
      this->_denom[i] = denom_partF*denom_partG*denom_partH*denom_partI;
    }
  }
int ShapeFunction< Simplex< 3 > >::getDegree () const [inline]
Retorna o grau do polinômio.
Definition at line 646 of file shapefunctions.hpp.
  {
    return _degree;
  }
int ShapeFunction< Simplex< 3 > >::getNumDof () const [inline]
Retorna o número de graus de liberdade.
Definition at line 653 of file shapefunctions.hpp.
References get_bit().
    {
        return (_degree+1)*(_degree+2)*(_degree+3)/6 + get_bit(_flags,0);
    }
Eigen::Vector3d ShapeFunction< Simplex< 3 > >::gradL (Eigen::Vector3d const & L, int ith) [inline]
Definition at line 639 of file shapefunctions.hpp.
References gradL().
  {
    return this->gradL(L[0], L[1], L[2], ith);
  }
Eigen::Vector3d ShapeFunction< Simplex< 3 > >::gradL (double L1, double L2, double L3, int ith) const [inline]
Retorna o gradiente no triangulo unitário, i.e.
Definition at line 576 of file shapefunctions.hpp.
References _ddxomega(), _omega(), _prod4(), and get_bit().
  {
    if ((ith<0) || (ith>=_ndof))
    {
      std::cout << "error:ShapeFunction::gradL(): invalid index." << std::endl;
      throw;
    }
    if (_degree == 0)
      return Eigen::Vector3d(0,0,0);
    double L0 = 1.-L1-L2-L3;
    int Q1 = this->_bar_nodes[ith][0],
      Q2 = this->_bar_nodes[ith][1],
      Q3 = this->_bar_nodes[ith][2],
      Q0 = this->_degree-Q1-Q2-Q3,
      n  = _degree;
    Eigen::Vector3d V;
    /* função bolha */
    if (get_bit(_flags,0) && (ith==_ndof-1))
    {
      V[0] = 256.*L2*L3*(L0-L1);
      V[1] = 256.*L1*L3*(L0-L2);
      V[2] = 256.*L1*L2*(L0-L3);
      return V;
    }
    /* lembrete: ddL1 = -ddL0 */
    V[0] = -_ddxomega(n, Q0, L0)*_omega(n, Q1, L1)*_omega(n, Q2, L2)*_omega(n, Q3, L3) +
          _ddxomega(n, Q1, L1)*_omega(n, Q0, L0)*_omega(n, Q2, L2)*_omega(n, Q3, L3);
    /* lembrete: ddL2 = -ddL0 */
    V[1] = -_ddxomega(n, Q0, L0)*_omega(n, Q1, L1)*_omega(n, Q2, L2)*_omega(n, Q3, L3) +
          _ddxomega(n, Q2, L2)*_omega(n, Q1, L1)*_omega(n, Q0, L0)*_omega(n, Q3, L3);
    /* lembrete: ddL3 = -ddL0 */
    V[2] = -_ddxomega(n, Q0, L0)*_omega(n, Q1, L1)*_omega(n, Q2, L2)*_omega(n, Q3, L3) +
          _ddxomega(n, Q3, L3)*_omega(n, Q1, L1)*_omega(n, Q2, L2)*_omega(n, Q0, L0);
    /* correção da bolha */
    if (get_bit(_flags,0) && (!get_bit(_flags,1)))
    {
      V[0] -= pow(4,4-_degree)*_prod4(_degree, Q0)*
                     _prod4(_degree, Q1)*
                   _prod4(_degree, Q2)*
                   _prod4(_degree, Q3)* L2*L3*(L0-L1);
      V[1] -= pow(4,4-_degree)*_prod4(_degree, Q0)*
                     _prod4(_degree, Q1)*
                   _prod4(_degree, Q2)*
                   _prod4(_degree, Q3)* L1*L3*(L0-L2);
      V[2] -= pow(4,4-_degree)*_prod4(_degree, Q0)*
                     _prod4(_degree, Q1)*
                   _prod4(_degree, Q2)*
                   _prod4(_degree, Q3)* L1*L2*(L0-L3);
    }
    return V/_denom[ith];
  }
double ShapeFunction< Simplex< 3 > >::operator() (Eigen::Vector3d const & L, int ith) const [inline]
Retorna a função avaliada nas coordenadas (L1, L2) do triângulo unitário
Definition at line 567 of file shapefunctions.hpp.
  {
    return this->operator()(L[0], L[1], L[2], ith);
  }
double ShapeFunction< Simplex< 3 > >::operator() (double L1, double L2, double L3, int ith) const [inline]
Retorna a função avaliada nas coordenadas (L1, L2) do triângulo unitário
Definition at line 523 of file shapefunctions.hpp.
References _omega(), _prod4(), and get_bit().
  {
    if ((ith<0) || (ith>=_ndof))
    {
      std::cout << "error:ShapeFunction::operator(): invalid index." << std::endl;
      throw;
    }
    if (_degree==0)
    {
      return 1.;
    }
    /* função bolha */
    if (get_bit(_flags,0) && (ith==_ndof-1))
    {
      return 256.*(1.-L1-L2-L3)*L1*L2*L3;
    }
    double L0 = 1.-L1-L2-L3;
    int Q1 = this->_bar_nodes[ith][0],
      Q2 = this->_bar_nodes[ith][1],
      Q3 = this->_bar_nodes[ith][2],
      Q0 = this->_degree-Q1-Q2-Q3;
    double result = _omega(_degree, Q0, L0)*
                    _omega(_degree, Q1, L1)*
                    _omega(_degree, Q2, L2)*
                    _omega(_degree, Q3, L3);
    /* correção da bolha */
    if (get_bit(_flags,0) && (!get_bit(_flags,1)))
    {
      result -= pow(4,4-_degree)*_prod4(_degree, Q0)*
                     _prod4(_degree, Q1)*
                     _prod4(_degree, Q2)*
                     _prod4(_degree, Q3)* (L0*L1*L2*L3);
    }
    return result / _denom[ith];
  }
void ShapeFunction< Simplex< 3 > >::setDegree (int degree) [inline]
Definition at line 459 of file shapefunctions.hpp.
References genTetParametricPtsINT(), get_bit(), and set_bit().
  {
    if (get_bit(_flags,1))
      set_bit(_flags,0);
    _ndof = (degree+1)*(degree+2)*(degree+3)/6 + get_bit(_flags,0);
    this->_bar_nodes = genTetParametricPtsINT(degree);
    this->calculateDenomList();
        _degree = degree;
  }
void ShapeFunction< Simplex< 3 > >::setDegree (int degree, char flags) [inline]
Defini o grau de função de lagrange.
Parameters:
degree o grau
flags os flags indicando se é uma função enriquecida, etc ...
são 8 bits:
bit0 se com bolha
bit1 se com bolha hierárquica
Note:
se setar o bit1 automaticamente é setado o bit0
Definition at line 478 of file shapefunctions.hpp.
  {
    _flags = flags;
    this->setDegree(degree);
  }
Member Data Documentation
std::vector<Eigen::Vector3i> ShapeFunction< Simplex< 3 > >::_bar_nodes
Definition at line 658 of file shapefunctions.hpp.
int ShapeFunction< Simplex< 3 > >::_degree
Definition at line 660 of file shapefunctions.hpp.
std::vector<long int> ShapeFunction< Simplex< 3 > >::_denom
Definition at line 659 of file shapefunctions.hpp.
char ShapeFunction< Simplex< 3 > >::_flags
Definition at line 661 of file shapefunctions.hpp.
int ShapeFunction< Simplex< 3 > >::_ndof
Definition at line 662 of file shapefunctions.hpp.
The documentation for this class was generated from the following file:
shapefunctions.hpp