FEPiCpp: MeshMethods< Mesh, 3 > Class Template Reference
MeshMethods< Mesh, 3 > Class Template Reference
#include <metamesh.hpp>
Static Public Member Functions
template<class Traits >
static void buildAdjacency (iMesh< Traits > &mesh)
template<class T >
static void remodelCellsNodes (iMesh< T > &mesh, int order)
template<class Traits >
static void buildCellLocalNodes (iMesh< Traits > &mesh)
Detailed Description
template<class Mesh>
class MeshMethods< Mesh, 3 >
Definition at line 40 of file metamesh.hpp.
Member Function Documentation
template<class Mesh > template<class Traits > static void MeshMethods< Mesh, 3 >::buildAdjacency (iMesh< Traits > & mesh) [inline, static]
Definition at line 44 of file metamesh.hpp.
References iMesh< Traits >::buildAdjacency4volume().
  {
    mesh.buildAdjacency4volume();
  }
template<class Mesh > template<class Traits > static void MeshMethods< Mesh, 3 >::buildCellLocalNodes (iMesh< Traits > & mesh) [inline, static]
Definition at line 56 of file metamesh.hpp.
References iMesh< Traits >::edges_local_nodes, iMesh< Traits >::faces_local_nodes, and iMesh< Traits >::getOrder().
    {
        mesh.edges_local_nodes = Traits::CellT::getEdgesLocalNodes(mesh.getOrder());
        mesh.faces_local_nodes = Traits::CellT::getFacesLocalNodes(mesh.getOrder());
    }
template<class Mesh > template<class T > static void MeshMethods< Mesh, 3 >::remodelCellsNodes (iMesh< T > & mesh, int order) [inline, static]
Definition at line 50 of file metamesh.hpp.
References iMesh< Traits >::remodelCellsNodes4volume().
    {
        mesh.remodelCellsNodes4volume(order);
    }
The documentation for this class was generated from the following file:
metamesh.hpp