FEPiCpp: iLabelable Class Reference
iLabelable Class Reference
#include <ilabelable.hpp>
Inherited by Edge< Traits >, iHalfEdgeLab< Traits >, iHalfFaceLab< Traits >, iPoint< Traits >, iPolygon< Traits >, and iPolyhedron< Traits >.
Public Member Functions
iLabelable (int Label, bool Isdead=false, bool MustBK=false, bool otherf=false)
iLabelable ()
int getLabel () const
void setLabel (unsigned char const &c)
void resetFlags ()
bool isDead () const
bool mustBeKilled () const
void killMe ()
void reviveMe ()
void killMeLater ()
void dontKillMe ()
~iLabelable ()
Static Protected Attributes
static const unsigned char FlagsMask = 7
static const int OffSet = 3
Detailed Description
Interface para armazenar um rótulo e 3 flags. Esses atributos são compactados em um único char. Os 3 primeiros bits do char são para armazenar os flags:
char[0] := "isdead" ?;
char[1] := "must be killed" ?;
char[2] := "other flags"
O restante é para armazenar o rótulo (inteiro de 0 a 31 se o char for de 8 bits).
Definition at line 39 of file ilabelable.hpp.
Constructor & Destructor Documentation
iLabelable::iLabelable (int Label, bool Isdead = false, bool MustBK = false, bool otherf = false) [inline]
Parameters:
Label O rótulo (inteiro de 0 a 31).
Isdead true se está morto ou false caso contrário.
MustBK true se deve ser morto ou false caso contrário.
otherf Um flag qualquer. Ainda não lhe foi atribuído nenhuma função.
Definition at line 47 of file ilabelable.hpp.
References OffSet, set_bit(), and unset_bit().
  {
    _label = (unsigned char)(Label << OffSet);
    Isdead ? set_bit(_label,0) : unset_bit(_label,0);
    MustBK ? set_bit(_label,1) : unset_bit(_label,1);
    otherf ? set_bit(_label,2) : unset_bit(_label,2);
  }
iLabelable::iLabelable () [inline]
Definition at line 55 of file ilabelable.hpp.
  {
    _label = 0;
  };
iLabelable::~iLabelable () [inline]
Definition at line 124 of file ilabelable.hpp.
{}
Member Function Documentation
void iLabelable::dontKillMe () [inline]
Limpa o flag "must be killed".
Definition at line 120 of file ilabelable.hpp.
References unset_bit().
                    {
    unset_bit(_label,1);
  }
int iLabelable::getLabel () const [inline]
Returns:
O rótulo.
Definition at line 62 of file ilabelable.hpp.
References OffSet.
Referenced by iPolyhedron< Traits >::propagateLabel(), iPolygon< Traits >::propagateLabel(), iHalfFaceLab< Traits >::propagateLabel(), and iHalfEdgeLab< Traits >::propagateLabel().
  {
    return int(_label >> OffSet);
  }
bool iLabelable::isDead () const [inline]
Returns:
true se está morto ou false caso contrário.
Definition at line 85 of file ilabelable.hpp.
References get_bit().
  {
    return get_bit(_label,0);
  }
void iLabelable::killMe () [inline]
Seta o flag "isdead".
Definition at line 99 of file ilabelable.hpp.
References set_bit().
  {
    set_bit(_label,0);
  }
void iLabelable::killMeLater () [inline]
Seta o flag "must be killed".
Definition at line 113 of file ilabelable.hpp.
References set_bit().
  {
    set_bit(_label,1);
  }
bool iLabelable::mustBeKilled () const [inline]
Returns:
true se deve ser morto ou false caso contrário.
Definition at line 92 of file ilabelable.hpp.
References get_bit().
  {
    return get_bit(_label,1);
  }
void iLabelable::resetFlags () [inline]
Limpa os flags.
Definition at line 78 of file ilabelable.hpp.
References FlagsMask.
  {
    _label &= (~FlagsMask);
  }
void iLabelable::reviveMe () [inline]
Limpa o flag "isdead".
Definition at line 106 of file ilabelable.hpp.
References unset_bit().
  {
    unset_bit(_label,0);
  }
void iLabelable::setLabel (unsigned char const & c) [inline]
Seta o rótulo.
Parameters:
c O rótulo.
Definition at line 70 of file ilabelable.hpp.
References FlagsMask, and OffSet.
  {
    _label &= FlagsMask;
    _label |= (c << OffSet);
  }
Member Data Documentation
const unsigned char iLabelable::FlagsMask = 7 [static, protected]
Definition at line 130 of file ilabelable.hpp.
Referenced by resetFlags(), and setLabel().
const int iLabelable::OffSet = 3 [static, protected]
Definition at line 131 of file ilabelable.hpp.
Referenced by getLabel(), iLabelable(), and setLabel().
The documentation for this class was generated from the following file:
ilabelable.hpp