FEPiCpp: iHalfFaceLab< Traits > Class Template Reference
iHalfFaceLab< Traits > Class Template Reference
#include <ihalffacelab.hpp>
Inherits iHalfFace< Traits >, and iLabelable.
Public Types
typedef Traits::MeshT MeshT
typedef Traits::CellT CellT
Public Member Functions
iHalfFaceLab (uint cellid, int ith, int anchor, int label=0)
iHalfFaceLab ()
void propagateHalf (MeshT &mesh) const
void propagateLabel (MeshT &mesh, bool force=false) const
~iHalfFaceLab ()
Detailed Description
template<class Traits>
class iHalfFaceLab< Traits >
Trata-se da classe iHalfFace com herança de classe iLabelable.
Definition at line 33 of file ihalffacelab.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::CellT iHalfFaceLab< Traits >::CellT
Definition at line 38 of file ihalffacelab.hpp.
template<class Traits > typedef Traits::MeshT iHalfFaceLab< Traits >::MeshT
Definition at line 37 of file ihalffacelab.hpp.
Constructor & Destructor Documentation
template<class Traits > iHalfFaceLab< Traits >::iHalfFaceLab (uint cellid, int ith, int anchor, int label = 0) [inline]
Construtor.
Parameters:
cellid o iD da célula incidente.
ith a posição da aresta nesta célula.
anchor o índice âncora.
label o rótulo.
Definition at line 47 of file ihalffacelab.hpp.
                                                              : iHalfFace<Traits> (cellid, ith, anchor),
                                                                                                                                  iLabelable(label) {}
template<class Traits > iHalfFaceLab< Traits >::iHalfFaceLab () [inline]
Definition at line 50 of file ihalffacelab.hpp.
: iHalfFace<Traits>(), iLabelable() {}
template<class Traits > iHalfFaceLab< Traits >::~iHalfFaceLab () [inline]
Destrutor.
Definition at line 84 of file ihalffacelab.hpp.
{}
Member Function Documentation
template<class Traits > void iHalfFaceLab< Traits >::propagateHalf (MeshT & mesh) const [inline]
Faz com que cada nó desta iHalfFaceLab aponte para ela.
Parameters:
mesh a malha na qual a iHalfFaceLab está contida.
Definition at line 55 of file ihalffacelab.hpp.
References iHalfFace< Traits >::getIDCell(), and iHalfFace< Traits >::getIDPosition().
  {
    Fepic::vectorui v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(),mesh );
    for (uint i = 0; i < v.size(); i++)
    {
      mesh.getNode(v[i])->setHalf(*this);
    }
  }
template<class Traits > void iHalfFaceLab< Traits >::propagateLabel (MeshT & mesh, bool force = false) const [inline]
Atribui o rótulo desta iHalfEdgeLab a seus nós.
Parameters:
force quando true indica atribuição incondicional, quando false, a atribuição é feita somente se cada nó tem label=0;
Definition at line 69 of file ihalffacelab.hpp.
References iHalfFace< Traits >::getIDCell(), iHalfFace< Traits >::getIDPosition(), and iLabelable::getLabel().
  {
    Fepic::vectori v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(),mesh );
    if (force)
      for (int i = 0; i < v.size(); ++i)
        mesh.getNode(v[i])->setLabel(this->getLabel());
    else
      for (int i = 0; i < v.size(); i++)
        if (mesh.getNode(v[i])->getLabel() == 0)
          mesh.getNode(v[i])->setLabel(this->getLabel());
  }
The documentation for this class was generated from the following file:
ihalffacelab.hpp