FEPiCpp: HalfFaceLab< Traits > Class Template Reference
HalfFaceLab< Traits > Class Template Reference
#include <halffacelab.hpp>
Inherits HalfFace< Traits >, and _Labelable.
Public Types
typedef Traits::MeshT MeshT
typedef Traits::CellT CellT
Public Member Functions
HalfFaceLab (uint incid_cell, int ith, int anchor, int tag=0)
HalfFaceLab ()
void propagateHalf (MeshT &mesh) const
void propagateTag (MeshT &mesh, bool force=false) const
~HalfFaceLab ()
Detailed Description
template<class Traits>
class HalfFaceLab< Traits >
Trata-se da classe HalfFace com herança de classe _Labelable.
Definition at line 33 of file halffacelab.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::CellT HalfFaceLab< Traits >::CellT
Definition at line 38 of file halffacelab.hpp.
template<class Traits > typedef Traits::MeshT HalfFaceLab< Traits >::MeshT
Definition at line 37 of file halffacelab.hpp.
Constructor & Destructor Documentation
template<class Traits > HalfFaceLab< Traits >::HalfFaceLab (uint incid_cell, int ith, int anchor, int tag = 0) [inline]
Construtor.
Parameters:
incid_cell o iD da célula incidente.
ith a posição da aresta nesta célula.
anchor o índice âncora.
tag o rótulo.
Definition at line 47 of file halffacelab.hpp.
template<class Traits > HalfFaceLab< Traits >::HalfFaceLab () [inline]
Definition at line 49 of file halffacelab.hpp.
template<class Traits > HalfFaceLab< Traits >::~HalfFaceLab () [inline]
Destrutor.
Definition at line 83 of file halffacelab.hpp.
Member Function Documentation
template<class Traits > void HalfFaceLab< Traits >::propagateHalf (MeshT & mesh) const [inline]
Faz com que cada nó desta HalfFaceLab aponte para ela.
Parameters:
mesh a malha na qual a HalfFaceLab está contida.
Definition at line 54 of file halffacelab.hpp.
References _HalfThingCore< HalfFace< Traits > >::getPosition().
template<class Traits > void HalfFaceLab< Traits >::propagateTag (MeshT & mesh, bool force = false) const [inline]
Atribui o rótulo desta HalfEdgeLab a seus nós.
Parameters:
force quando true indica atribuição incondicional, quando false, a atribuição é feita somente se cada nó tem tag=0;
Definition at line 68 of file halffacelab.hpp.
References _HalfThingCore< HalfFace< Traits > >::getPosition(), and _Labelable::getTag().
The documentation for this class was generated from the following file:
halffacelab.hpp