FEPiCpp: HalfFace< Traits > Class Template Reference
HalfFace< Traits > Class Template Reference
#include <halfface.hpp>
Inherits _HalfThingCore< HalfFace< Traits > >.
Inherited by HalfFaceLab< Traits >.
Public Types
enum { cell_id_limit = 134217727 }
enum { position_limit = 6 }
enum { anchor_limit = 3 }
typedef Traits::MeshT MeshT
typedef Traits::CellT CellT
Public Member Functions
HalfFace (uint incid_cell, int position, int anchor)
HalfFace ()
void printSelf (std::ostream &o) const
~HalfFace ()
Static Public Member Functions
static std::string getName ()
Protected Attributes
uint _incid_cell: 27
uint _position: 3
uint _anchor: 2
Friends
class _HalfThingCore< HalfEdge< Traits > >
Detailed Description
template<class Traits>
class HalfFace< Traits >
Definition at line 28 of file halfface.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::CellT HalfFace< Traits >::CellT
Definition at line 32 of file halfface.hpp.
template<class Traits > typedef Traits::MeshT HalfFace< Traits >::MeshT
Definition at line 31 of file halfface.hpp.
Member Enumeration Documentation
template<class Traits > anonymous enum
Enumerator:
cell_id_limit
Definition at line 34 of file halfface.hpp.
template<class Traits > anonymous enum
Enumerator:
position_limit
Definition at line 35 of file halfface.hpp.
template<class Traits > anonymous enum
Enumerator:
anchor_limit
Definition at line 36 of file halfface.hpp.
Constructor & Destructor Documentation
template<class Traits > HalfFace< Traits >::HalfFace (uint incid_cell, int position, int anchor) [inline]
Definition at line 40 of file halfface.hpp.
template<class Traits > HalfFace< Traits >::HalfFace () [inline]
Construtor.
Definition at line 47 of file halfface.hpp.
template<class Traits > HalfFace< Traits >::~HalfFace () [inline]
Destrutor.
Definition at line 69 of file halfface.hpp.
Member Function Documentation
template<class Traits > static std::string HalfFace< Traits >::getName () [inline, static]
Returns:
uma string com o nome Half-Face.
Definition at line 62 of file halfface.hpp.
template<class Traits > void HalfFace< Traits >::printSelf (std::ostream & o) const [inline]
Imprime em um stream a composição do iD, i.e, imprime
getIncidCell() << " " << getPosition() << " " << getAnchor()
Parameters:
o o stream onde se vai escrever.
Definition at line 55 of file halfface.hpp.
References _HalfThingCore< HalfFace< Traits > >::getAnchor(), _HalfThingCore< HalfFace< Traits > >::getIncidCell(), and _HalfThingCore< HalfFace< Traits > >::getPosition().
Friends And Related Function Documentation
template<class Traits > friend class _HalfThingCore< HalfEdge< Traits > > [friend]
Definition at line 38 of file halfface.hpp.
Member Data Documentation
template<class Traits > uint HalfFace< Traits >::_anchor [protected]
Definition at line 73 of file halfface.hpp.
template<class Traits > uint HalfFace< Traits >::_incid_cell [protected]
Definition at line 71 of file halfface.hpp.
template<class Traits > uint HalfFace< Traits >::_position [protected]
Definition at line 72 of file halfface.hpp.
The documentation for this class was generated from the following file:
halfface.hpp