FEPiCpp: iHalfEdgeLab< Traits > Class Template Reference
iHalfEdgeLab< Traits > Class Template Reference
#include <ihalfedgelab.hpp>
Inherits iHalfEdge< Traits >, and iLabelable.
Public Types
typedef Traits::MeshT MeshT
Public Member Functions
iHalfEdgeLab (uint cellid, int ith, int label=0)
iHalfEdgeLab ()
void propagateHalf (MeshT &mesh) const
void propagateLabel (MeshT &mesh, bool force=false) const
~iHalfEdgeLab ()
Detailed Description
template<class Traits>
class iHalfEdgeLab< Traits >
Trata-se da classe iHalfEdge com herança de classe iLabelable.
Definition at line 31 of file ihalfedgelab.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::MeshT iHalfEdgeLab< Traits >::MeshT
Definition at line 35 of file ihalfedgelab.hpp.
Constructor & Destructor Documentation
template<class Traits > iHalfEdgeLab< Traits >::iHalfEdgeLab (uint cellid, int ith, int label = 0) [inline]
Construtor.
Parameters:
cellid O iD da célula incidente.
ith A posição da aresta nesta célula.
label o rótulo.
Definition at line 42 of file ihalfedgelab.hpp.
                                                  : iHalfEdge<Traits>(cellid, ith),
                                                                                                          iLabelable(label) {}
template<class Traits > iHalfEdgeLab< Traits >::iHalfEdgeLab () [inline]
Definition at line 44 of file ihalfedgelab.hpp.
: iHalfEdge<Traits>(), iLabelable() {};
template<class Traits > iHalfEdgeLab< Traits >::~iHalfEdgeLab () [inline]
Destrutor.
Definition at line 77 of file ihalfedgelab.hpp.
{}
Member Function Documentation
template<class Traits > void iHalfEdgeLab< Traits >::propagateHalf (MeshT & mesh) const [inline]
Faz com que cada nó desta iHalfEdgeLab aponte para ela.
Parameters:
mesh a malha na qual a iHalfEdgeLab está contida.
Definition at line 49 of file ihalfedgelab.hpp.
References iHalfEdge< Traits >::getIDCell(), and iHalfEdge< Traits >::getIDPosition().
  {
    Fepic::vectorui v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(), mesh );
    for (uint i = 0; i < v.size(); i++)
      mesh.getNode(v[i])->setHalf(*this);
  }
template<class Traits > void iHalfEdgeLab< Traits >::propagateLabel (MeshT & mesh, bool force = false) const [inline]
Atribui o rótulo desta iHalfEdgeLab a seus nós.
Parameters:
force quando true indica atribuição incondicional, quando false, a atribuição é feita somente se cada nó tem label=0;
Definition at line 62 of file ihalfedgelab.hpp.
References iHalfEdge< Traits >::getIDCell(), iHalfEdge< Traits >::getIDPosition(), and iLabelable::getLabel().
  {
    Fepic::vectori v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(), mesh);
    if (force)
      for (int i = 0; i < v.size(); ++i)
        mesh.getNode(v[i])->setLabel(this->getLabel());
    else
      for (int i = 0; i < v.size(); i++)
        if (mesh.getNode(v[i])->getLabel() == 0)
          mesh.getNode(v[i])->setLabel(this->getLabel());
  }
The documentation for this class was generated from the following file:
ihalfedgelab.hpp