FEPiCpp: iHalfFace< Traits > Class Template Reference
iHalfFace< Traits > Class Template Reference
#include <entities.hpp>
Inherited by iMarkedHalfFace< Traits >.
Public Types
typedef Traits::MeshT MeshT
typedef Traits::CellT CellT
Public Member Functions
iHalfFace (uint cellid, int ith, int anchor)
iHalfFace ()
uint getIDCell () const
int getIDPosition () const
int getIDAnchor () const
void setIDCell (uint cellid)
void setIDPosition (int ith)
void setIDAnchor (int anchor)
void setCompleteID (uint v, int ith, int anchor)
void printSelf (std::ostream &o) const
Fepic::vectorui getVertices (MeshT &mesh)
Fepic::vectorui getNodes (MeshT &mesh)
bool hasTheseVertices (Fepic::vectorui const &v, MeshT &mesh)
~iHalfFace ()
Static Public Member Functions
static std::string getName ()
Protected Attributes
uint _compositeID
Static Protected Attributes
static const uint AnchorMask = 3
static const uint IndexMask = 28
static const uint FlagsMask = 31
static const uint IdMask = (~31)
static const int OffSet0 = 2
static const int OffSet1 = 5
Detailed Description
template<class Traits>
class iHalfFace< Traits >
Armazena o iD da célula incidente, o seu índice local em relação a esta célula e a sua âncora (ver definição no final da descrição).
O iD da iHalfEdge é feita da seguinte composição
<v, ith, anchor>
onde
v := iD da célula (poliedro) [ 27bits ]
ith := i-ésima face desse volume [ 3bits ]
anchor := k-ésimo nó da face do volume [ 2bits ]
Essas informações são armazenadas em uma única variável (uint) [32bits] usando manipulação de bits. Os limites de v, ith e anchor são, respectivamente:
0 <= v <= 134 217 727
-1 <= ith <= 6
0 <= anchor <= 4
definição para âncora : dada uma iHalfFace que contenha os vértices n0,n1,...,nB, se ela é a face F e âncora A de um poliedro, então, o nó B-A é o primeiro nó da face F do poliedro.
Definition at line 578 of file entities.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::CellT iHalfFace< Traits >::CellT
Definition at line 582 of file entities.hpp.
template<class Traits > typedef Traits::MeshT iHalfFace< Traits >::MeshT
Definition at line 581 of file entities.hpp.
Constructor & Destructor Documentation
template<class Traits > iHalfFace< Traits >::iHalfFace (uint cellid, int ith, int anchor) [inline]
Parameters:
cellid O iD da célula incidente.
ith A posição da face nesta célula.
anchor O índice âncora.
Definition at line 588 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, iHalfFace< Traits >::OffSet0, and iHalfFace< Traits >::OffSet1.
        {
                /* <v, ith, anchor>
                  27b   3b    2b    */
                _compositeID = (cellid << OffSet1);
                _compositeID |= ((uint)(ith+1) << OffSet0);
                _compositeID |= (uint)(anchor);
        }
template<class Traits > iHalfFace< Traits >::iHalfFace () [inline]
Construtor.
Definition at line 600 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, and iHalfFace< Traits >::setIDPosition().
        {
                this->_compositeID = 0;
        this->setIDPosition(-1);
        }
template<class Traits > iHalfFace< Traits >::~iHalfFace () [inline]
Destrutor.
Definition at line 724 of file entities.hpp.
{}
Member Function Documentation
template<class Traits > int iHalfFace< Traits >::getIDAnchor () const [inline]
Returns:
O índice âncora
Definition at line 622 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, and iHalfFace< Traits >::AnchorMask.
Referenced by iHalfFace< Traits >::printSelf().
        {
                return _compositeID & AnchorMask;
        }
template<class Traits > uint iHalfFace< Traits >::getIDCell () const [inline]
Returns:
iD da célula incidente
Definition at line 608 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, and iHalfFace< Traits >::OffSet1.
Referenced by iHalfFace< Traits >::getNodes(), iHalfFace< Traits >::getVertices(), iHalfFace< Traits >::hasTheseVertices(), iHalfFace< Traits >::printSelf(), iMarkedHalfFace< Traits >::propagateHalf(), and iMarkedHalfFace< Traits >::propagateLabel().
        {
                return _compositeID >> OffSet1;
        }
template<class Traits > int iHalfFace< Traits >::getIDPosition () const [inline]
Returns:
A posição desta iHalfFace na célula
Definition at line 615 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, iHalfFace< Traits >::IndexMask, and iHalfFace< Traits >::OffSet0.
Referenced by iHalfFace< Traits >::getNodes(), iHalfFace< Traits >::getVertices(), iHalfFace< Traits >::hasTheseVertices(), iHalfFace< Traits >::printSelf(), iMarkedHalfFace< Traits >::propagateHalf(), and iMarkedHalfFace< Traits >::propagateLabel().
        {
                return ((_compositeID & IndexMask) >> OffSet0) - 1;
        }
template<class Traits > static std::string iHalfFace< Traits >::getName () [inline, static]
Returns:
uma string com o nome Half-Face.
Definition at line 679 of file entities.hpp.
        {
                return std::string("Half-Face");
        }
template<class Traits > Fepic::vectorui iHalfFace< Traits >::getNodes (MeshT & mesh) [inline]
Retorna um vetor com os índices dos nós que esta iHalfFace contém.
Parameters:
mesh a malha na qual a iHalfFace está contida.
Definition at line 697 of file entities.hpp.
References iHalfFace< Traits >::getIDCell(), and iHalfFace< Traits >::getIDPosition().
    {
        CellT *cell = mesh.getCell(this->getIDCell());
        return cell->getBorderNodes(this->getIDPosition(), mesh);
    }
template<class Traits > Fepic::vectorui iHalfFace< Traits >::getVertices (MeshT & mesh) [inline]
Retorna um vetor com os índices dos vértices que esta iHalfFace contém.
Parameters:
mesh a malha na qual a iHalfFace está contida.
Definition at line 687 of file entities.hpp.
References iHalfFace< Traits >::getIDCell(), and iHalfFace< Traits >::getIDPosition().
    {
        CellT *cell = mesh.getCell(this->getIDCell());
        return cell->getBorderVertices(this->getIDPosition(), mesh);
    }
template<class Traits > bool iHalfFace< Traits >::hasTheseVertices (Fepic::vectorui const & v, MeshT & mesh) [inline]
Verifica se esta iHalfFace contém exatamente os vértices (índices) passados em v.
Parameters:
v vetor com os índices dos vértices.
mesh a malha na qual esta iHalfFace está contida.
Returns:
true se os nós formam a iHalfFace e false caso contrário.
Note:
Os nós podem estar em qualquer orientação cíclica da original.
Definition at line 711 of file entities.hpp.
References arrayIsCyclicallyEqual(), iHalfFace< Traits >::getIDCell(), and iHalfFace< Traits >::getIDPosition().
        {
                Fepic::vectorui vtx(mesh.faces_local_nodes[0].size());
                CellT *cell = mesh.getCell(this->getIDCell());
                vtx = cell->getBorderVertices(this->getIDPosition()) ;
                return arrayIsCyclicallyEqual(v, vtx);
        }
template<class Traits > void iHalfFace< Traits >::printSelf (std::ostream & o) const [inline]
Imprime em um stream a composição do iD, i.e, imprime
getIDCell() << " " << getIDPosition() << " " << getIDAnchor()
Parameters:
o o stream onde se vai escrever.
Definition at line 672 of file entities.hpp.
References iHalfFace< Traits >::getIDAnchor(), iHalfFace< Traits >::getIDCell(), and iHalfFace< Traits >::getIDPosition().
        {
                o << getIDCell() << " " << getIDPosition() << " " << getIDAnchor();
        }
template<class Traits > void iHalfFace< Traits >::setCompleteID (uint v, int ith, int anchor) [inline]
Parameters:
cellid O iD da célula incidente.
ith O índice local desta iHalfFace na célula incidente.
anchor O índice âncora.
Definition at line 658 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, iHalfFace< Traits >::OffSet0, and iHalfFace< Traits >::OffSet1.
        {
                /* <v, ith, anchor>
                    R   3b    2b    */
                _compositeID = (v << OffSet1);
                _compositeID |= ((uint)(ith+1) << OffSet0);
                _compositeID |= (uint)(anchor);
        }
template<class Traits > void iHalfFace< Traits >::setIDAnchor (int anchor) [inline]
Seta o índice âncora.
Parameters:
anchor O índice âncora.
Definition at line 648 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, and iHalfFace< Traits >::AnchorMask.
        {
                _compositeID &= ~AnchorMask;
                _compositeID |= (uint)(anchor);
        }
template<class Traits > void iHalfFace< Traits >::setIDCell (uint cellid) [inline]
Seta o iD da célula incidente.
Parameters:
cellid O índice da célula.
Definition at line 630 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, iHalfFace< Traits >::FlagsMask, and iHalfFace< Traits >::OffSet1.
        {
                _compositeID &= FlagsMask;
                _compositeID |= (cellid << OffSet1);
        }
template<class Traits > void iHalfFace< Traits >::setIDPosition (int ith) [inline]
Seta o índice local da iHalfFace na célula incidente.
Parameters:
ith o índice.
Definition at line 639 of file entities.hpp.
References iHalfFace< Traits >::_compositeID, iHalfFace< Traits >::IndexMask, and iHalfFace< Traits >::OffSet0.
Referenced by iHalfFace< Traits >::iHalfFace().
        {
                _compositeID &= ~IndexMask;
                _compositeID |= (uint)(ith+1) << OffSet0;
        }
Member Data Documentation
template<class Traits > uint iHalfFace< Traits >::_compositeID [protected]
Definition at line 726 of file entities.hpp.
Referenced by iHalfFace< Traits >::getIDAnchor(), iHalfFace< Traits >::getIDCell(), iHalfFace< Traits >::getIDPosition(), iHalfFace< Traits >::iHalfFace(), iHalfFace< Traits >::setCompleteID(), iHalfFace< Traits >::setIDAnchor(), iHalfFace< Traits >::setIDCell(), and iHalfFace< Traits >::setIDPosition().
template<class Traits > const uint iHalfFace< Traits >::AnchorMask = 3 [static, protected]
Definition at line 727 of file entities.hpp.
Referenced by iHalfFace< Traits >::getIDAnchor(), and iHalfFace< Traits >::setIDAnchor().
template<class Traits > const uint iHalfFace< Traits >::FlagsMask = 31 [static, protected]
Definition at line 729 of file entities.hpp.
Referenced by iHalfFace< Traits >::setIDCell().
template<class Traits > const uint iHalfFace< Traits >::IdMask = (~31) [static, protected]
Definition at line 730 of file entities.hpp.
template<class Traits > const uint iHalfFace< Traits >::IndexMask = 28 [static, protected]
Definition at line 728 of file entities.hpp.
Referenced by iHalfFace< Traits >::getIDPosition(), and iHalfFace< Traits >::setIDPosition().
template<class Traits > const int iHalfFace< Traits >::OffSet0 = 2 [static, protected]
Definition at line 731 of file entities.hpp.
Referenced by iHalfFace< Traits >::getIDPosition(), iHalfFace< Traits >::iHalfFace(), iHalfFace< Traits >::setCompleteID(), and iHalfFace< Traits >::setIDPosition().
template<class Traits > const int iHalfFace< Traits >::OffSet1 = 5 [static, protected]
Definition at line 732 of file entities.hpp.
Referenced by iHalfFace< Traits >::getIDCell(), iHalfFace< Traits >::iHalfFace(), iHalfFace< Traits >::setCompleteID(), and iHalfFace< Traits >::setIDCell().
The documentation for this class was generated from the following file:
entities.hpp