FEPiCpp: HalfEdge< Traits > Class Template Reference
HalfEdge< Traits > Class Template Reference
#include <halfedge.hpp>
Inherits _HalfThingCore< HalfEdge< Traits > >.
Inherited by HalfEdgeLab< Traits >.
Public Types
enum { cell_id_limit = 134217727 }
enum { position_limit = 6 }
enum { anchor_limit = 3 }
typedef Traits::MeshT MeshT
typedef Traits::CellT CellT
Public Member Functions
HalfEdge (uint incid_cell, int position, int=0)
HalfEdge ()
void printSelf (std::ostream &o)
double getLenght (MeshT &mesh) const
~HalfEdge ()
Static Public Member Functions
static std::string getName ()
Protected Attributes
uint _incid_cell: 27
uint _position: 3
uint _anchor: 2
Friends
class _HalfThingCore< HalfEdge< Traits > >
Detailed Description
template<class Traits>
class HalfEdge< Traits >
Definition at line 28 of file halfedge.hpp.
Member Typedef Documentation
template<class Traits> typedef Traits::CellT HalfEdge< Traits >::CellT
Definition at line 32 of file halfedge.hpp.
template<class Traits> typedef Traits::MeshT HalfEdge< Traits >::MeshT
Definition at line 31 of file halfedge.hpp.
Member Enumeration Documentation
template<class Traits> anonymous enum
Enumerator:
cell_id_limit
Definition at line 34 of file halfedge.hpp.
template<class Traits> anonymous enum
Enumerator:
position_limit
Definition at line 35 of file halfedge.hpp.
template<class Traits> anonymous enum
Enumerator:
anchor_limit
Definition at line 36 of file halfedge.hpp.
Constructor & Destructor Documentation
template<class Traits> HalfEdge< Traits >::HalfEdge (uint incid_cell, int position, int = 0) [inline]
Definition at line 40 of file halfedge.hpp.
template<class Traits> HalfEdge< Traits >::HalfEdge () [inline]
Construtor.
Definition at line 47 of file halfedge.hpp.
template<class Traits> HalfEdge< Traits >::~HalfEdge () [inline]
Destrutor.
Definition at line 82 of file halfedge.hpp.
Member Function Documentation
template<class Traits> double HalfEdge< Traits >::getLenght (MeshT & mesh) const [inline]
Retorna o comprimento da HalfEdge, i.e., da aresta que ela representa.
Definition at line 63 of file halfedge.hpp.
References _HalfThingCore< HalfEdge< Traits > >::getNodes().
template<class Traits> static std::string HalfEdge< Traits >::getName () [inline, static]
Returns:
uma string contendo "Half-Edge"
Definition at line 75 of file halfedge.hpp.
template<class Traits> void HalfEdge< Traits >::printSelf (std::ostream & o) [inline]
Imprime a composição do iD desta HalfEdge.
Parameters:
o o stream onde se vai escrever, e.g., std::cout.
Definition at line 55 of file halfedge.hpp.
References _HalfThingCore< HalfEdge< Traits > >::getIncidCell(), and _HalfThingCore< HalfEdge< Traits > >::getPosition().
Friends And Related Function Documentation
template<class Traits> friend class _HalfThingCore< HalfEdge< Traits > > [friend]
Definition at line 38 of file halfedge.hpp.
Member Data Documentation
template<class Traits> uint HalfEdge< Traits >::_anchor [protected]
Definition at line 87 of file halfedge.hpp.
template<class Traits> uint HalfEdge< Traits >::_incid_cell [protected]
Definition at line 85 of file halfedge.hpp.
template<class Traits> uint HalfEdge< Traits >::_position [protected]
Definition at line 86 of file halfedge.hpp.
The documentation for this class was generated from the following file:
halfedge.hpp