FEPiCpp: iMarkedHalfEdge< Traits > Class Template Reference
iMarkedHalfEdge< Traits > Class Template Reference
#include <entities.hpp>
Inherits iHalfEdge< Traits >, and iMarkedEntity.
Public Types
typedef Traits::MeshT MeshT
Public Member Functions
iMarkedHalfEdge (uint cellid, int ith, int label=0)
iMarkedHalfEdge ()
void propagateHalf (MeshT &mesh) const
void propagateLabel (MeshT &mesh, bool force=false) const
~iMarkedHalfEdge ()
Detailed Description
template<class Traits>
class iMarkedHalfEdge< Traits >
Trata-se da classe iHalfEdge com herança de classe iMarkedEntity.
Definition at line 743 of file entities.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::MeshT iMarkedHalfEdge< Traits >::MeshT
Definition at line 747 of file entities.hpp.
Constructor & Destructor Documentation
template<class Traits > iMarkedHalfEdge< Traits >::iMarkedHalfEdge (uint cellid, int ith, int label = 0) [inline]
Construtor.
Parameters:
cellid O iD da célula incidente.
ith A posição da aresta nesta célula.
label o rótulo.
Definition at line 754 of file entities.hpp.
                                                           : iHalfEdge<Traits>(cellid, ith),
                                                                                                                 iMarkedEntity(label) {}
template<class Traits > iMarkedHalfEdge< Traits >::iMarkedHalfEdge () [inline]
Definition at line 756 of file entities.hpp.
: iHalfEdge<Traits>(), iMarkedEntity() {};
template<class Traits > iMarkedHalfEdge< Traits >::~iMarkedHalfEdge () [inline]
Destrutor.
Definition at line 801 of file entities.hpp.
{}
Member Function Documentation
template<class Traits > void iMarkedHalfEdge< Traits >::propagateHalf (MeshT & mesh) const [inline]
Faz com que cada nó desta iMarkedHalfEdge aponte para ela.
Parameters:
mesh a malha na qual a iMarkedHalfEdge está contida.
Definition at line 761 of file entities.hpp.
References iHalfEdge< Traits >::getIDCell(), and iHalfEdge< Traits >::getIDPosition().
        {
                Fepic::vectorui v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(), mesh );
                for (uint i = 0; i < v.size(); i++)
                {
                        mesh.getNode(v[i])->setHalf(*this);
                }
        }
template<class Traits > void iMarkedHalfEdge< Traits >::propagateLabel (MeshT & mesh, bool force = false) const [inline]
Atribui o rótulo desta iMarkedHalfEdge a seus nós.
Parameters:
force quando true indica atribuição incondicional, quando false, a atribuição é feita somente se cada nó tem label=0;
Definition at line 776 of file entities.hpp.
References iHalfEdge< Traits >::getIDCell(), iHalfEdge< Traits >::getIDPosition(), and iMarkedEntity::getLabel().
        {
                Fepic::vectori v = mesh.getCell( this->getIDCell() )->getBorderNodes( this->getIDPosition(), mesh);
                if (force)
                {
                        for (int i = 0; i < v.size(); ++i)
{
                                mesh.getNode(v[i])->setLabel(this->getLabel());
                        }
                }
                else
                {
                        for (int i = 0; i < v.size(); i++)
{
                                if (mesh.getNode(v[i])->getLabel() == 0)
{
                                        mesh.getNode(v[i])->setLabel(this->getLabel());
                                }
                        }
                }
        }
The documentation for this class was generated from the following file:
entities.hpp