FEPiCpp: iHalfEdge< Traits > Class Template Reference
iHalfEdge< Traits > Class Template Reference
#include <entities.hpp>
Inherited by iMarkedHalfEdge< Traits >.
Public Types
typedef Traits::MeshT MeshT
typedef Traits::CellT CellT
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
iHalfEdge (uint cellid, int ith, int=0)
iHalfEdge ()
uint getIDCell () const
int getIDPosition () const
void setIDCell (uint cellid)
void setIDPosition (int ith)
void setCompleteID (uint cellid, int ith)
void printSelf (std::ostream &o) const
double getLenght (MeshT &mesh) const
Fepic::vectorui getVertices (MeshT &mesh)
Fepic::vectorui getNodes (MeshT &mesh) const
bool hasTheseVertices (Fepic::vectorui const &v, MeshT &mesh) const
~iHalfEdge ()
Static Public Member Functions
static std::string getName ()
Protected Attributes
uint _compositeID
Static Protected Attributes
static const uint IndexMask = 15
static const int OffSet = 4
Detailed Description
template<class Traits>
class iHalfEdge< Traits >
Armazena o iD da célula incidente e o seu índice local em relação a esta célula.
O iD da iHalfEdge é feita da seguinte composição
<f, ith>
onde
f:= iD da célula (polígono) [ 28bits ]
ith := i-ésima aresta desta célula [ 4bits ]
Essas informações são armazenadas em uma única variável (uint) [32bits] usando manipulação de bits. Os valores de f e ith estão, respectivamente, na faixa:
0 <= f <= 268 435 456
-1 <= ith <= 14
Warning:
o tipo unsigned int deve ter 32 bits.
Definition at line 401 of file entities.hpp.
Member Typedef Documentation
template<class Traits> typedef Traits::CellT iHalfEdge< Traits >::CellT
Definition at line 406 of file entities.hpp.
template<class Traits> typedef Traits::MeshT iHalfEdge< Traits >::MeshT
Definition at line 405 of file entities.hpp.
template<class Traits> typedef Eigen::Matrix<double, Traits::spacedim, 1> iHalfEdge< Traits >::VecT
Definition at line 408 of file entities.hpp.
Constructor & Destructor Documentation
template<class Traits> iHalfEdge< Traits >::iHalfEdge (uint cellid, int ith, int = 0) [inline]
Construtor.
Parameters:
cellid O iD da célula incidente.
ith A posição da aresta nesta célula.
Definition at line 414 of file entities.hpp.
References iHalfEdge< Traits >::_compositeID, and iHalfEdge< Traits >::OffSet.
        {
                _compositeID = (cellid << OffSet);
                _compositeID |= (uint)(ith+1);
                /* atenção na soma de 1 : é um truque para mais tarde poder retornar -1 */
        }
template<class Traits> iHalfEdge< Traits >::iHalfEdge () [inline]
Construtor.
Definition at line 423 of file entities.hpp.
References iHalfEdge< Traits >::_compositeID, and iHalfEdge< Traits >::setIDPosition().
        {
                this->_compositeID = 0;
        this->setIDPosition(-1);
        }
template<class Traits> iHalfEdge< Traits >::~iHalfEdge () [inline]
Destrutor.
Definition at line 540 of file entities.hpp.
{}
Member Function Documentation
template<class Traits> uint iHalfEdge< Traits >::getIDCell () const [inline]
Returns:
iD da célula incidente (triângulo, quadrângulo, ...)
Definition at line 431 of file entities.hpp.
References iHalfEdge< Traits >::_compositeID, and iHalfEdge< Traits >::OffSet.
Referenced by iHalfEdge< Traits >::getNodes(), iHalfEdge< Traits >::getVertices(), iHalfEdge< Traits >::hasTheseVertices(), iHalfEdge< Traits >::printSelf(), iMarkedHalfEdge< Traits >::propagateHalf(), and iMarkedHalfEdge< Traits >::propagateLabel().
        {
                return _compositeID >> OffSet;
        }
template<class Traits> int iHalfEdge< Traits >::getIDPosition () const [inline]
Returns:
A posição desta iHalfEdge na célula
Definition at line 438 of file entities.hpp.
References iHalfEdge< Traits >::_compositeID, and iHalfEdge< Traits >::IndexMask.
Referenced by iHalfEdge< Traits >::getNodes(), iHalfEdge< Traits >::getVertices(), iHalfEdge< Traits >::hasTheseVertices(), iHalfEdge< Traits >::printSelf(), iMarkedHalfEdge< Traits >::propagateHalf(), and iMarkedHalfEdge< Traits >::propagateLabel().
        {
                return (_compositeID & IndexMask) - 1;
        }
template<class Traits> double iHalfEdge< Traits >::getLenght (MeshT & mesh) const [inline]
Retorna o comprimento da iHalfEdge, i.e., da aresta que ela representa.
Definition at line 481 of file entities.hpp.
References iHalfEdge< Traits >::getNodes().
    {
        Fepic::vectorui nodes(std::move(this->getNodes(mesh)));
        double sum=0;
        for (int i = 0; i < nodes.size()-1; i++)
        {
            sum += mesh.getNode(nodes[i])->getDistance(*mesh.getNode(nodes[i+1]));
        }
        return sum;
    }
template<class Traits> static std::string iHalfEdge< Traits >::getName () [inline, static]
Returns:
uma string contendo "Half-Edge"
Definition at line 533 of file entities.hpp.
        {
                return std::string("Half-Edge");
        }
template<class Traits> Fepic::vectorui iHalfEdge< Traits >::getNodes (MeshT & mesh) const [inline]
Retorna um vetor com os índices dos nós que esta iHalfEdge contém.
Parameters:
mesh a malha na qual a iHalfEdge está contida.
Definition at line 506 of file entities.hpp.
References iHalfEdge< Traits >::getIDCell(), and iHalfEdge< Traits >::getIDPosition().
Referenced by iHalfEdge< Traits >::getLenght().
    {
        CellT *cell = mesh.getCell(this->getIDCell());
        return cell->getBorderNodes(this->getIDPosition(),mesh);
    }
template<class Traits> Fepic::vectorui iHalfEdge< Traits >::getVertices (MeshT & mesh) [inline]
Retorna um vetor com os índices dos vértices que esta iHalfEdge contém.
Parameters:
mesh a malha na qual a iHalfEdge está contida.
Definition at line 496 of file entities.hpp.
References iHalfEdge< Traits >::getIDCell(), and iHalfEdge< Traits >::getIDPosition().
    {
        CellT *cell = mesh.getCell(this->getIDCell());
        return cell->getBorderVertices(this->getIDPosition());
    }
template<class Traits> bool iHalfEdge< Traits >::hasTheseVertices (Fepic::vectorui const & v, MeshT & mesh) const [inline]
Verifica se esta iHalfEdge contém exatamente os vértices (índices) passados em v.
Parameters:
v vetor com os índices dos vértices.
mesh a malha na qual esta iHalfEdge está contida.
Returns:
true se os nós formam a iHalfEdge e false caso contrário.
Note:
Os nós podem estar em qualquer orientação cíclica da original.
Definition at line 520 of file entities.hpp.
References arrayIsCyclicallyEqual(), iHalfEdge< Traits >::getIDCell(), and iHalfEdge< Traits >::getIDPosition().
        {
                Fepic::vectorui vtx(2);
                CellT *cell = mesh.getCell(this->getIDCell());
                vtx = cell->getBorderVertices(this->getIDPosition()) ;
                return arrayIsCyclicallyEqual(v, vtx);
        }
template<class Traits> void iHalfEdge< Traits >::printSelf (std::ostream & o) const [inline]
Imprime a composição do iD desta iHalfEdge.
Parameters:
o o stream onde se vai escrever, e.g., std::cout.
Definition at line 473 of file entities.hpp.
References iHalfEdge< Traits >::getIDCell(), and iHalfEdge< Traits >::getIDPosition().
        {
                o << getIDCell() << " " << getIDPosition();
        }
template<class Traits> void iHalfEdge< Traits >::setCompleteID (uint cellid, int ith) [inline]
Parameters:
cellid O iD da célula incidente.
ith A posição da aresta nesta célula.
Definition at line 464 of file entities.hpp.
References iHalfEdge< Traits >::_compositeID, and iHalfEdge< Traits >::OffSet.
        {
                _compositeID = (cellid << OffSet);
                _compositeID |= (uint)(ith+1);
        }
template<class Traits> void iHalfEdge< Traits >::setIDCell (uint cellid) [inline]
Seta o iD da célula incidente.
Parameters:
cellid índice da célula.
Definition at line 446 of file entities.hpp.
References iHalfEdge< Traits >::_compositeID, iHalfEdge< Traits >::IndexMask, and iHalfEdge< Traits >::OffSet.
        {
                _compositeID &= IndexMask;
                _compositeID |= (cellid << OffSet);
        }
template<class Traits> void iHalfEdge< Traits >::setIDPosition (int ith) [inline]
Seta a posição da HE na célula.
Parameters:
ith A posição.
Definition at line 455 of file entities.hpp.
References iHalfEdge< Traits >::_compositeID, and iHalfEdge< Traits >::IndexMask.
Referenced by iHalfEdge< Traits >::iHalfEdge().
        {
                _compositeID &= ~IndexMask;
                _compositeID |= (uint)(ith+1);
        }
Member Data Documentation
template<class Traits> uint iHalfEdge< Traits >::_compositeID [protected]
Definition at line 543 of file entities.hpp.
Referenced by iHalfEdge< Traits >::getIDCell(), iHalfEdge< Traits >::getIDPosition(), iHalfEdge< Traits >::iHalfEdge(), iHalfEdge< Traits >::setCompleteID(), iHalfEdge< Traits >::setIDCell(), and iHalfEdge< Traits >::setIDPosition().
template<class Traits> const uint iHalfEdge< Traits >::IndexMask = 15 [static, protected]
Definition at line 544 of file entities.hpp.
Referenced by iHalfEdge< Traits >::getIDPosition(), iHalfEdge< Traits >::setIDCell(), and iHalfEdge< Traits >::setIDPosition().
template<class Traits> const int iHalfEdge< Traits >::OffSet = 4 [static, protected]
Definition at line 545 of file entities.hpp.
Referenced by iHalfEdge< Traits >::getIDCell(), iHalfEdge< Traits >::iHalfEdge(), iHalfEdge< Traits >::setCompleteID(), and iHalfEdge< Traits >::setIDCell().
The documentation for this class was generated from the following file:
entities.hpp