FEPiCpp: iPolygon< Traits > Class Template Reference
iPolygon< Traits > Class Template Reference
#include <ipolygon.hpp>
Inherits iLabelable.
Inherited by Triangle< Traits >.
Public Types
typedef Traits::CellT FaceT
typedef Traits::MeshT MeshT
typedef Eigen::Matrix< double,
Traits::spacedim, 1 > VecT
Public Member Functions
iPolygon ()
iPolygon (Fepic::vectorui const &nodes, int label=0)
int getNumNodes () const
uint getNodeIdx (int ith) const
void setNode (int ith, uint nodeid)
iHalfEdge< Traits > * getHalf (int ith)
bool isAnEdge (Fepic::vectorui const &vertices, int &ith) const
bool isAnParallelEdge (Fepic::vectorui &&vertices, int &ith) const
bool getCommonBorder (FaceT *other, int &thisborder, int &otherborder) const
void propagateHalf (MeshT &mesh) const
void propagateLabel (MeshT &mesh, bool force=false) const
Fepic::vectorui getBorderNodes (int ith, MeshT &mesh) const
Fepic::vectorui getBorderVertices (int ith) const
void printSelfState (std::ostream &o) const
Static Public Attributes
static const int Dim = 2
static const int N_borders = ElementProperties<FaceT, Traits>::N_borders
static const int N_vertices = ElementProperties<FaceT, Traits>::N_vertices
Detailed Description
template<class Traits>
class iPolygon< Traits >
A classe iPolygon representa os polígonos (triângulo, quadrângulos, ...), entidades da malha de dimensão 2. Dependendo da ordem, os polígonos dessa classe podem ter arestas curvas.
Note:
Esta é uma classe de conceito abstrato (apesar se não ser abstrata sob o ponto de vista da linguagem c++ pois não tem funções virtuais puras), logo não se deve instanciá-la a não ser que se saiba exatamente o que se está fazendo.
Definition at line 35 of file ipolygon.hpp.
Member Typedef Documentation
template<class Traits > typedef Traits::CellT iPolygon< Traits >::FaceT
Reimplemented in Triangle< Traits >.
Definition at line 41 of file ipolygon.hpp.
template<class Traits > typedef Traits::MeshT iPolygon< Traits >::MeshT
Reimplemented in Triangle< Traits >.
Definition at line 42 of file ipolygon.hpp.
template<class Traits > typedef Eigen::Matrix<double, Traits::spacedim, 1> iPolygon< Traits >::VecT
Reimplemented in Triangle< Traits >.
Definition at line 47 of file ipolygon.hpp.
Constructor & Destructor Documentation
template<class Traits > iPolygon< Traits >::iPolygon () [inline]
Construtor.
Definition at line 51 of file ipolygon.hpp.
References iPolygon< Traits >::N_vertices.
             : iLabelable()
  {
    _node.resize(N_vertices);
  }
template<class Traits > iPolygon< Traits >::iPolygon (Fepic::vectorui const & nodes, int label = 0) [inline]
Construtor.
Parameters:
nodes vetor com os nós que compõe o iPolygon.
Definition at line 59 of file ipolygon.hpp.
References iPolygon< Traits >::N_vertices.
                                                    : iLabelable(label), _node(nodes)
  {
#ifdef FEPIC_DEBUG_ON
    if (_node.size() < static_cast<uint>(N_vertices))
    {
      std::cout << "error:iPolygon constructor: número insuficiente de nós.\n";
      throw;
    }
#endif
  }
Member Function Documentation
template<class Traits > Fepic::vectorui iPolygon< Traits >::getBorderNodes (int ith, MeshT & mesh) const [inline]
Retorna um vetor com os nós da i-ésima edge.
Definition at line 242 of file ipolygon.hpp.
  {
    Fepic::vectorui nodes;
    for (uint i = 0; i < mesh.edges_local_nodes[ith].size(); i++)
      nodes.push_back(_node[ mesh.edges_local_nodes[ith][i] ]);
    return nodes;
  }
template<class Traits > Fepic::vectorui iPolygon< Traits >::getBorderVertices (int ith) const [inline]
Retorna um vetor com os vértices da i-ésima edge
Definition at line 253 of file ipolygon.hpp.
References iPolygon< Traits >::N_borders.
Referenced by iPolygon< Traits >::getCommonBorder().
  {
#ifdef FEPIC_DEBUG_ON
    if (ith >= N_borders)
    {
      std::cout << "getCommonBorder: null FaceT.\n" << std::endl;
      throw;
    }
#endif
    return {_node[ith], _node[(ith+1)%FaceT::N_borders]};
  }
template<class Traits > bool iPolygon< Traits >::getCommonBorder (FaceT * other, int & thisborder, int & otherborder) const [inline]
OBSOLETO: refazer
Procura por uma edge em comum com outro polígono: se encontra retorna true, caso contrário retorna false.
Definition at line 177 of file ipolygon.hpp.
References iPolygon< Traits >::getBorderVertices(), and iPolygon< Traits >::N_borders.
  {
#ifdef FEPIC_DEBUG_ON
    if (other==NULL)
    {
      std::cout << "getCommonBorder: null FaceT.\n" << std::endl;
      throw;
    }
#endif
    Fepic::vectorui this_edge_vtx(2);
    for (int s = 0; s < N_borders; ++s)
    {
      this_edge_vtx = this->getBorderVertices(s);
      reverse(this_edge_vtx.begin(), this_edge_vtx.end());
      if (other->isAnEdge(this_edge_vtx, otherborder))
      {
        thisborder = s;
        return true;
      }
    }
    return false;
  }
template<class Traits > iHalfEdge<Traits>* iPolygon< Traits >::getHalf (int ith) [inline]
Retorna um ponteiro para a i-ésima iHalfEdge.
Definition at line 101 of file ipolygon.hpp.
References iPolygon< Traits >::N_borders.
  {
#ifdef FEPIC_DEBUG_ON
    if (ith >= N_borders)
    {
      std::cout << "getHalf: out of range" << std::endl;
      throw;
    }
#endif
    return &_he[ith];
  }
template<class Traits > uint iPolygon< Traits >::getNodeIdx (int ith) const [inline]
Retorna o índice do i-ésimo nó do polígono.
Definition at line 79 of file ipolygon.hpp.
Referenced by iPolygon< Traits >::printSelfState(), and Triangle< Traits >::printSelfVTK().
  {
#ifdef FEPIC_DEBUG_ON
    return _node.at(ith);
#else
    return _node[ith];
#endif
  }
template<class Traits > int iPolygon< Traits >::getNumNodes () const [inline]
Retorna o número de nós deste polígono.
Definition at line 72 of file ipolygon.hpp.
  {
    return _node.size();
  }
template<class Traits > bool iPolygon< Traits >::isAnEdge (Fepic::vectorui const & vertices, int & ith) const [inline]
Retorna se os vertices passados formam uma aresta do polígono.
Parameters:
[in] vertices um vetor com exatamente 2 vertices.
[out] ith o índice local da aresta que os pontos formam.
Returns:
true se e somente se forma uma aresta.
Warning:
a ordem dos nós É importante.
Definition at line 119 of file ipolygon.hpp.
References iPolygon< Traits >::N_borders.
Referenced by iPolygon< Traits >::isAnParallelEdge().
  {
#ifdef FEPIC_DEBUG_ON
    if (vertices.size() != 2)
    {
      std::cout << "isAnEdge: first argument has wrong dimension.\n" << std::endl;
      throw;
    }
#endif
    Fepic::vectorui vtx(2);
    for (int i = 0; i != N_borders; ++i)
    {
      vtx[0] = _node[i];
      vtx[1] = _node[(i+1)%N_borders];
      if (vtx == vertices)
      {
        ith = i;
        return true;
      }
    }
    return false;
  }
template<class Traits > bool iPolygon< Traits >::isAnParallelEdge (Fepic::vectorui && vertices, int & ith) const [inline]
Retorna se os vertices passados formam uma aresta do polígono.
Parameters:
[in] vertices um vetor com exatamente 2 vertices.
[out] ith o índice local da aresta que os pontos formam.
Returns:
true se e somente se forma uma aresta.
Warning:
a ordem dos nós NÃO é importante.
Definition at line 151 of file ipolygon.hpp.
References iPolygon< Traits >::isAnEdge().
  {
#ifdef FEPIC_DEBUG_ON
    if (vertices.size() != 2)
    {
      std::cout << "isAnEdge: first argument has wrong dimension.\n" << std::endl;
      throw;
    }
#endif
    if (this->isAnEdge(vertices, ith))
      return true;
    std::swap(vertices[0], vertices[1]);
    if (this->isAnEdge(vertices, ith))
    {
      std::swap(vertices[0], vertices[1]);
      return true;
    }
    std::swap(vertices[0], vertices[1]);
    return false;
  }
template<class Traits > void iPolygon< Traits >::printSelfState (std::ostream & o) const [inline]
Imprime este polígono no formato State (seus nós).
Parameters:
o a stream onde se vai imprimir, e.g., std::cout.
Definition at line 268 of file ipolygon.hpp.
References iPolygon< Traits >::getNodeIdx().
  {
    o << getNodeIdx(0);
    for (uint i = 1; i < _node.size(); ++i)
      o << " " << getNodeIdx(i);
  }
template<class Traits > void iPolygon< Traits >::propagateHalf (MeshT & mesh) const [inline]
Atribui em cada nó deste polígono uma iHalfEdge compatível.
Parameters:
mesh a malha em que este polígono está contido.
Definition at line 205 of file ipolygon.hpp.
References iPolygon< Traits >::N_borders.
  {
#ifdef FEPIC_DEBUG_ON
    if (mesh.edges_local_nodes.empty())
    {
      std::cout << "edges_local_nodes must be initializated." << std::endl;
      throw;
    }
#endif
    for (uint s = 0; s < static_cast<uint>(N_borders); ++s) // loop  nas arestas
    {
      for (uint i = 0, tam=mesh.edges_local_nodes[0].size(); i < tam; ++i)
      {
        mesh.getNode(_node[mesh.edges_local_nodes[s][i]])->setHalf(_he[s]);
      }
    }
  }
template<class Traits > void iPolygon< Traits >::propagateLabel (MeshT & mesh, bool force = false) const [inline]
Atribui o rótulo deste polígono a seus nós.
Parameters:
mesh a malha em que este polígono está contido.
force quando true indica atribuição incondicional, quando false, a atribuição é feita somente se cada nó tem label=0;
Warning:
CONFERIR!
Definition at line 229 of file ipolygon.hpp.
References iLabelable::getLabel().
  {
    if (force)
      for (int i = 0; i < _node.size(); i++)
        mesh.getNode(_node[i])->setLabel(this->getLabel());
    else
      for (int i = 0; i < _node.size(); i++)
        if (mesh.getNode(_node[i])->getLabel() == 0)
          mesh.getNode(_node[i])->setLabel(this->getLabel());
  }
template<class Traits > void iPolygon< Traits >::setNode (int ith, uint nodeid) [inline]
Defini o i-ésimo nó do polígono como nodeid
Definition at line 90 of file ipolygon.hpp.
  {
#ifdef FEPIC_DEBUG_ON
    _node.at(ith) = nodeid;
#else
    _node[ith] = nodeid;
#endif
  }
Member Data Documentation
template<class Traits > const int iPolygon< Traits >::Dim = 2 [static]
Definition at line 38 of file ipolygon.hpp.
template<class Traits > const int iPolygon< Traits >::N_borders = ElementProperties<FaceT, Traits>::N_borders [static]
Reimplemented in Triangle< Traits >.
Definition at line 44 of file ipolygon.hpp.
Referenced by iPolygon< Traits >::getBorderVertices(), iPolygon< Traits >::getCommonBorder(), iPolygon< Traits >::getHalf(), iPolygon< Traits >::isAnEdge(), and iPolygon< Traits >::propagateHalf().
template<class Traits > const int iPolygon< Traits >::N_vertices = ElementProperties<FaceT, Traits>::N_vertices [static]
Reimplemented in Triangle< Traits >.
Definition at line 45 of file ipolygon.hpp.
Referenced by iPolygon< Traits >::iPolygon().
The documentation for this class was generated from the following file:
ipolygon.hpp