FEPiCpp: MeshMethods< Mesh, 2 > Class Template Reference
MeshMethods< Mesh, 2 > Class Template Reference
#include <metamesh.hpp>
Static Public Member Functions
template<class T >
static void buildAdjacency (iMesh< T > &mesh)
template<class T >
static void remodelCellsNodes (iMesh< T > &mesh, int order)
template<class T >
static void buildCellLocalNodes (iMesh< T > &mesh)
Detailed Description
template<class Mesh>
class MeshMethods< Mesh, 2 >
Definition at line 17 of file metamesh.hpp.
Member Function Documentation
template<class Mesh > template<class T > static void MeshMethods< Mesh, 2 >::buildAdjacency (iMesh< T > & mesh) [inline, static]
Definition at line 21 of file metamesh.hpp.
References iMesh< Traits >::buildAdjacency4face().
  {
    mesh.buildAdjacency4face();
  }
template<class Mesh > template<class T > static void MeshMethods< Mesh, 2 >::buildCellLocalNodes (iMesh< T > & mesh) [inline, static]
Definition at line 33 of file metamesh.hpp.
References iMesh< Traits >::edges_local_nodes, and iMesh< Traits >::getOrder().
    {
        mesh.edges_local_nodes = T::CellT::FaceT::getEdgesLocalNodes(mesh.getOrder());
    }
template<class Mesh > template<class T > static void MeshMethods< Mesh, 2 >::remodelCellsNodes (iMesh< T > & mesh, int order) [inline, static]
Definition at line 27 of file metamesh.hpp.
References iMesh< Traits >::remodelCellsNodes4face().
    {
        mesh.remodelCellsNodes4face(order);
    }
The documentation for this class was generated from the following file:
metamesh.hpp