FEPiCpp: _HalfThingCore< _Der > Class Template Reference
_HalfThingCore< _Der > Class Template Reference
#include <halfthingcore.hpp>
Public Member Functions
uint getIncidCell () const
int getPosition () const
uint getAnchor () const
void setIncidCell (uint cellid)
void setPosition (int pos)
void setAnchor (uint anchor)
void setCompleteId (uint cellid, int pos, uint anchor=0)
template<class Mesh >
Fepic::vectorui getVertices (Mesh const &mesh) const
template<class Mesh >
Fepic::vectorui getNodes (Mesh const &mesh) const
template<class Mesh >
bool hasTheseVertices (Fepic::vectorui const &v, Mesh const &mesh) const
Protected Member Functions
_HalfThingCore ()
_HalfThingCore (_HalfThingCore const &)
Detailed Description
template<class _Der>
class _HalfThingCore< _Der >
Definition at line 27 of file halfthingcore.hpp.
Constructor & Destructor Documentation
template<class _Der> _HalfThingCore< _Der >::_HalfThingCore () [inline, protected]
Definition at line 127 of file halfthingcore.hpp.
template<class _Der> _HalfThingCore< _Der >::_HalfThingCore (_HalfThingCore< _Der > const &) [inline, protected]
Definition at line 128 of file halfthingcore.hpp.
Member Function Documentation
template<class _Der> uint _HalfThingCore< _Der >::getAnchor () const [inline]
Definition at line 50 of file halfthingcore.hpp.
template<class _Der> uint _HalfThingCore< _Der >::getIncidCell () const [inline]
Definition at line 39 of file halfthingcore.hpp.
Referenced by _HalfThingCore< HalfFace< Traits > >::getNodes(), _HalfThingCore< HalfFace< Traits > >::getVertices(), and _HalfThingCore< HalfFace< Traits > >::hasTheseVertices().
template<class _Der> template<class Mesh > Fepic::vectorui _HalfThingCore< _Der >::getNodes (Mesh const & mesh) const [inline]
Retorna um vetor com os índices dos nós que esta HalfFace contém.
Parameters:
mesh a malha na qual a HalfFace está contida.
Definition at line 99 of file halfthingcore.hpp.
template<class _Der> int _HalfThingCore< _Der >::getPosition () const [inline]
Definition at line 45 of file halfthingcore.hpp.
Referenced by _HalfThingCore< HalfFace< Traits > >::getNodes(), and _HalfThingCore< HalfFace< Traits > >::getVertices().
template<class _Der> template<class Mesh > Fepic::vectorui _HalfThingCore< _Der >::getVertices (Mesh const & mesh) const [inline]
Retorna um vetor com os índices dos vértices que esta HalfFace contém.
Parameters:
mesh a malha na qual a HalfFace está contida.
Definition at line 87 of file halfthingcore.hpp.
template<class _Der> template<class Mesh > bool _HalfThingCore< _Der >::hasTheseVertices (Fepic::vectorui const & v, Mesh const & mesh) const [inline]
Verifica se esta HalfFace contém exatamente os vértices (índices) passados em v.
Parameters:
v vetor com os índices dos vértices.
mesh a malha na qual esta HalfFace está contida.
Returns:
true se os nós formam a HalfFace e false caso contrário.
Note:
Os nós podem estar em qualquer orientação cíclica da original.
Definition at line 115 of file halfthingcore.hpp.
template<class _Der> void _HalfThingCore< _Der >::setAnchor (uint anchor) [inline]
Definition at line 67 of file halfthingcore.hpp.
template<class _Der> void _HalfThingCore< _Der >::setCompleteId (uint cellid, int pos, uint anchor = 0) [inline]
Definition at line 73 of file halfthingcore.hpp.
template<class _Der> void _HalfThingCore< _Der >::setIncidCell (uint cellid) [inline]
Definition at line 55 of file halfthingcore.hpp.
template<class _Der> void _HalfThingCore< _Der >::setPosition (int pos) [inline]
Definition at line 61 of file halfthingcore.hpp.
The documentation for this class was generated from the following file:
halfthingcore.hpp