FEPiCpp: misc.hpp File Reference
misc.hpp File Reference
Classes
class M_IfThenElse< true, Ta, Tb >
class M_IfThenElse< false, Ta, Tb >
Namespaces
namespace Fepic
Typedefs
typedef std::vector
< std::vector< int > > Fepic::matrixi
typedef std::vector
< std::vector< uint > > Fepic::matrixUi
typedef std::vector
< std::vector< double > > Fepic::matrixd
typedef std::vector
< std::vector< bool > > Fepic::matrixb
typedef std::vector< double > Fepic::vectord
typedef std::vector< int > Fepic::vectori
typedef std::vector< bool > Fepic::vectorb
typedef std::vector< uint > Fepic::vectorui
typedef std::deque< uint > Fepic::dequeui
Functions
template<class T >
const T & Fepic::max (const T &a)
template<class T , class... O>
const T & Fepic::max (const T &a, const O &...b)
template<class In_it , class Out_it >
void copy_from (In_it a_begin, Out_it c_begin, Out_it c_end)
template<class T >
bool arrayIsCyclicallyEqual (std::vector< T > const &v1, std::vector< T > const &v2)
template<class T >
void printArray (T const &v, std::ostream &o, int N)
template<class T >
void printMatrix (T const &mat, std::ostream &o, int N, int M)
size_t search_word (std::ifstream &File, const char *word)
template<class T >
bool get_bit (T const &c, unsigned bitoffset)
template<class T >
void set_bit (T &c, unsigned bitoffset)
template<class T >
void unset_bit (T &c, unsigned bitoffset)
Function Documentation
template<class T > bool arrayIsCyclicallyEqual (std::vector< T > const & v1, std::vector< T > const & v2)
Verifica se dois vetores são (anti)ciclicamente iguais. TESTAR, POIS FIZ MUDANÇAS
Definition at line 79 of file misc.hpp.
Referenced by iHalfFace< Traits >::hasTheseVertices(), and iHalfEdge< Traits >::hasTheseVertices().
{
  std::vector<T> vaux(v2);
  uint vsize = v2.size();
  auto vaux_begin = vaux.begin(), vaux_end = vaux.end();
  for (uint i = 0; i < vsize; ++i)
  {
    if (v1 == vaux)
    {
      return true;
    }
    rotate(vaux_begin, vaux_begin+1, vaux_end);
  }
  reverse(vaux_begin, vaux_end);
  if(vaux == v1) return true;
  for (uint i = 1; i < vsize; ++i)
  {
    rotate(vaux_begin, vaux_begin+1, vaux_end);
    if (v1 == vaux)
    {
      return true;
    }
  }
  return false;
}
template<class In_it , class Out_it > void copy_from (In_it a_begin, Out_it c_begin, Out_it c_end) [inline]
função parecida com a copy do STL.
copia o conteúdo de uma sequência `a' para outra `c' no intervalo [c_begin, c_end).
Parameters:
a_begin iterador na posição inicial da sequência `a'
c_begin iterador na posição inicial da sequência `c' (c de cópia)
c_end iterador na posição final da seguência (excluindo o último elemento)
Definition at line 63 of file misc.hpp.
{
  while(c_begin != c_end) *c_begin++ = *a_begin++;
}
template<class T > bool get_bit (T const & c, unsigned bitoffset) [inline]
Retorna o n-ésimo bit da constante c passada.
Definition at line 163 of file misc.hpp.
Referenced by ShapeFunction< Simplex< 3 > >::getNumDof(), ShapeFunction< Simplex< 2 > >::getNumDof(), ShapeFunction< Simplex< 3 > >::gradL(), ShapeFunction< Simplex< 2 > >::gradL(), iLabelable::isDead(), iLabelable::mustBeKilled(), ShapeFunction< Simplex< 3 > >::operator()(), ShapeFunction< Simplex< 2 > >::operator()(), ShapeFunction< Simplex< 3 > >::setDegree(), ShapeFunction< Simplex< 2 > >::setDegree(), ShapeFunction< Simplex< 3 > >::ShapeFunction(), and ShapeFunction< Simplex< 2 > >::ShapeFunction().
{
    T bitmask = ( 1 << bitoffset) ;
    return ((c & bitmask)!=0) ? 1 : 0;
}
template<class T > void printArray (T const & v, std::ostream & o, int N) [inline]
Definition at line 112 of file misc.hpp.
{
  o << v[0];
  for (int i=1; i<N; ++i)
  {
    o << " " << v[i];
  }
}
template<class T > void printMatrix (T const & mat, std::ostream & o, int N, int M) [inline]
Definition at line 123 of file misc.hpp.
{
  for (int i = 0; i < N; i++)
  {
    for (int j = 0; j < M; j++)
    {
      o << mat[i][j] << " ";
    }
    o << std::endl;
  }
}
size_t search_word (std::ifstream & File, const char * word) [inline]
Definition at line 139 of file misc.hpp.
Referenced by iMesh< Traits >::readFileMSH().
{
  std::string s;
  std::string word_s = std::string(word);
    do
  {
    s="";
    File >> s;
    if (File.peek()==EOF)
    {
      std::cout << "Incorrect file format" << std::endl;
      return -1;
    }
  } while(s!=word_s);
  return size_t(File.tellg());
}
template<class T > void set_bit (T & c, unsigned bitoffset) [inline]
Seta o n-ésimo bit da constante c passada.
Definition at line 172 of file misc.hpp.
Referenced by iLabelable::iLabelable(), iLabelable::killMe(), iLabelable::killMeLater(), ShapeFunction< Simplex< 3 > >::setDegree(), ShapeFunction< Simplex< 2 > >::setDegree(), ShapeFunction< Simplex< 3 > >::ShapeFunction(), and ShapeFunction< Simplex< 2 > >::ShapeFunction().
{
    T bitmask = 1 << bitoffset;
    c = (c | bitmask);
}
template<class T > void unset_bit (T & c, unsigned bitoffset) [inline]
Zera o n-ésimo bit da constante c passada.
Definition at line 181 of file misc.hpp.
Referenced by iLabelable::dontKillMe(), iLabelable::iLabelable(), and iLabelable::reviveMe().
{
    T bitmask = 1 << bitoffset;
    c = (c & (~bitmask));
}