FEPiCpp: Fepic Namespace Reference
Fepic Namespace Reference
Typedefs
typedef std::vector
< std::vector< int > > matrixi
typedef std::vector
< std::vector< uint > > matrixUi
typedef std::vector
< std::vector< double > > matrixd
typedef std::vector
< std::vector< bool > > matrixb
typedef std::vector< double > vectord
typedef std::vector< int > vectori
typedef std::vector< bool > vectorb
typedef std::vector< uint > vectorui
typedef std::deque< uint > dequeui
Functions
template<class T >
const T & max (const T &a)
template<class T , class... O>
const T & max (const T &a, const O &...b)
Typedef Documentation
typedef std::deque<uint> Fepic::dequeui
Definition at line 25 of file misc.hpp.
typedef std::vector<std::vector<bool> > Fepic::matrixb
Definition at line 19 of file misc.hpp.
typedef std::vector<std::vector<double> > Fepic::matrixd
Definition at line 18 of file misc.hpp.
typedef std::vector<std::vector<int> > Fepic::matrixi
Definition at line 16 of file misc.hpp.
typedef std::vector<std::vector<uint> > Fepic::matrixUi
Definition at line 17 of file misc.hpp.
typedef std::vector<bool> Fepic::vectorb
Definition at line 23 of file misc.hpp.
typedef std::vector<double> Fepic::vectord
Definition at line 21 of file misc.hpp.
typedef std::vector<int> Fepic::vectori
Definition at line 22 of file misc.hpp.
typedef std::vector<uint> Fepic::vectorui
Definition at line 24 of file misc.hpp.
Function Documentation
template<class T > const T& Fepic::max (const T & a)
Definition at line 30 of file misc.hpp.
Referenced by ShapeFunction< Simplex< 3 > >::calculateDenomList(), ShapeFunction< Simplex< 2 > >::calculateDenomList(), and max().
{
    return a;
  }
template<class T , class... O> const T& Fepic::max (const T & a, const O &... b)
Definition at line 35 of file misc.hpp.
References max().
{
    auto& c(max(b...));
    return (c<a)?a:c;
  }